R20.1 254
tetonsim/is-cura-ui pull request #255
Opened 2020-09-02 22:30 UTC by dougkenik

Fix for weird text rendering issues in Login Screen when using QTQuick.Controls 1

2020-09-02 22:41 UTC, colman-hartinger requested changes
code looks good and login screen still works as expected.

2020-09-02 22:41 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/SmartSliceLogin.qml
> +        }
is this meant to be here still?

2020-09-02 22:44 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/SmartSliceLogin.qml
> +                            border.width: UM.Theme.getSize("default_lining").width;
random semicolon

2020-09-02 22:44 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/SmartSliceLogin.qml
> +                            border.width: UM.Theme.getSize("default_lining").width;
random semicolon

2020-09-03 00:00 UTC, bradymadams approved these changes

2020-09-03 13:04 UTC, merged