R20.1 260
tetonsim/is-cura-ui pull request #265
Opened 2020-09-04 03:57 UTC by dougkenik

I think this is ready for a draft review while I'm out of town. I am running into an issue trying to submit a job with a modifier mesh from an optimization job (smartslice 148), but other than that it is behaving as expected. Here is what I did:

- Created a new class to track properties for all scene nodes
- Decorated scene nodes that we programatically add / remove so we don't issue a revalidation  or reoptimization warning as we change results from the table
- Fixed the issue where deleting a modifier mesh will not invalidate results
- Enhanced this by also issuing a warning when the user deletes the root node (only node) during validation or optimization, or after optimized

2020-09-04 15:54 UTC, bradymadams requested changes

2020-09-04 15:54 UTC, bradymadams commented on SmartSlicePlugin/SmartSlicePropertyHandler.py
> +                changed.append(p)
How are `changed` and `changes` different? Is `changed` even used?

2020-09-04 15:54 UTC, bradymadams commented on SmartSlicePlugin/plugin.json
> +        "url": "https://test.smartslice.xyz:443",
I'm assuming unintentional. We need to implement a local config file so this isn't a recurring problem.

2020-09-04 15:54 UTC, bradymadams commented on SmartSlicePlugin/SmartSlicePropertyHandler.py
> +        controller.getScene().getRoot().childrenChanged.connect(self._onSceneNodeChanged)
Duplicate of line 107

2020-09-04 15:54 UTC, bradymadams commented on SmartSlicePlugin/SmartSlicePropertyHandler.py
> +            if p.changed() and not p != self._scene:
I believe `not p != self._scene` is equivalent to `p == self._scene`. The latter would be easier to read.

So this means we're only restoring the scene, right? Is that what we want?

2020-09-04 15:54 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceProperty.py
> +        return False
Not sure I understand this function. Don't we want to trigger `changed` if we detect a node has been added that we haven't seen yet. Maybe that gets done elsewhere?

2020-09-04 22:59 UTC, dougkenik commented on SmartSlicePlugin/SmartSlicePropertyHandler.py
> +                changed.append(p)
No. It was for a debug. Removed

2020-09-04 22:59 UTC, dougkenik commented on SmartSlicePlugin/plugin.json
> +        "url": "https://test.smartslice.xyz:443",
Unintentional. Agreed on creating something to make this easier

2020-09-04 23:01 UTC, dougkenik commented on SmartSlicePlugin/SmartSlicePropertyHandler.py
> +            if p.changed() and not p != self._scene:
Nope - leftover from a different way to do this

2020-09-04 23:04 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceProperty.py
> +        return False
The intent is to not return `True` if the changed node has a decorator which implies it has been programatically added / removed by Smart Slice. I'll move the functionality for caching into a different function and call it from the `onSceneNodeChanged `function

2020-09-06 23:00 UTC, dougkenik commented
We're ready for another review here

2020-09-07 13:43 UTC, bradymadams approved these changes

2020-09-07 13:45 UTC, merged