R20.2 280
tetonsim/is-cura-ui pull request #334
Opened 2020-09-23 20:35 UTC by dougkenik

Ok, this fixes #280 and needs to be validated a few different ways:

1. If a user brings in a normal and modifier mesh, runs a validation, and moves either mesh, it should invalidate results
2. Same with above but with opening a validation that has been ran and saved
2. If we run an optimization and insert a modifier mesh. If the user moves the normal mesh, the modifier mesh should move with it and not invalidate results. If the user moves the modifier mesh it should invalidate the results

2020-09-23 22:11 UTC, jake-kirkland-teton commented
So if you move something during a validate, then cancel it, it causes an error in the 3MF that is generated from there on out.

![CancelChangesGif](https://user-images.githubusercontent.com/62028020/94074849-4cf21f00-fdb7-11ea-9931-1d618ac73330.gif)

2020-09-23 22:14 UTC, dougkenik commented
> So if you move something during a validate, then cancel it, it causes an error in the 3MF that is generated from there on out.
> 
> ![CancelChangesGif](https://user-images.githubusercontent.com/62028020/94074849-4cf21f00-fdb7-11ea-9931-1d618ac73330.gif)

Save the 3mf and post it here so someone can look into why it's causing an issue

2020-09-23 22:18 UTC, jake-kirkland-teton commented
[UMS5_Flat_Bracket_modmesh_bug.zip](https://github.com/tetonsim/is-cura-ui/files/5272213/UMS5_Flat_Bracket_modmesh_bug.zip)

2020-09-23 22:23 UTC, dougkenik commented
> [UMS5_Flat_Bracket_modmesh_bug.zip](https://github.com/tetonsim/is-cura-ui/files/5272213/UMS5_Flat_Bracket_modmesh_bug.zip)

@bradymadams - can you look at that when you're free and let me know if anything strange stands out

2020-09-24 01:17 UTC, bradymadams commented
Our 3MF reader chokes on the empty arrays on the mod mesh settings. I opened an issue in pywim: https://github.com/tetonsim/pywim/issues/67. If I remove those settings it runs for me.

There are a lot of settings on that mod mesh. I'd remove any that aren't necessary - our 3MF reader struggles with those (also related to https://github.com/tetonsim/pywim/issues/63).

![image](https://user-images.githubusercontent.com/23110600/94089623-dcf09280-fdd0-11ea-9e56-5a3e5799d238.png)

2020-09-25 20:07 UTC, jake-kirkland-teton commented
So if the bug that was created is not problematic for closing this ticket, and we want to handle the bug that was created in a separate ticket, I approve.

2020-09-25 20:08 UTC, jake-kirkland-teton approved these changes

2020-09-25 20:16 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceProperty.py
> +        return None, None, None, None, []
I think the changes to this class may be cleaner if all the transform objects were added to an array

2020-09-25 20:18 UTC, colman-hartinger approved these changes
The code runs fine and couldn't find any bugs when, I have my  comment above a bout possibly putting all the transform objects into an array but I'm not sure if that's a viable option or not

2020-09-25 20:26 UTC, colman-hartinger commented
> 
>     3. If we run an optimization and insert a modifier mesh. If the user moves the normal mesh, the modifier mesh should move with it and not invalidate results. If the user moves the modifier mesh it should invalidate the results

I remember when I was working on the mod mesh validation ticket that the backend had some problems validating parts with mod meshes if the mod mesh is defined as a child of the printable node. I'm running on optimization right now so hold of on merging the code for a sec @bradymadams

2020-09-25 20:50 UTC, colman-hartinger requested changes
@dougkenik I would revert back to not having the modifier meshes as a child node of the printable mesh since the backend can't properly validate that.

2020-09-25 20:59 UTC, dougkenik commented
> @dougkenik I would revert back to not having the modifier meshes as a child node of the printable mesh since the backend can't properly validate that.

We cannot do that because the position of the meshes will get messed up on project open. What is the message from the back end?

2020-09-25 21:07 UTC, colman-hartinger commented
> We cannot do that because the position of the meshes will get messed up on project open. What is the message from the back end?

It's not that you get an error from the backend its that the transformation gets messed up during validation. I didn't save the optimized job I just ran but I'll run another to post for example.

The problem is that the results will be vastly different from the optimized results. So if you take a part with a modifier mesh that  you just got back from an optimization and then go back to validate it with the exact same loading and anchors you will get very different results when the modifier mesh is defined as a child of the printable node. In my test using a brake lever with a modifier mesh generated from an optimization the results were a fos: 1.6 and max displacement: 3.45 under the same loading and anchors in validation the results went up to fos: 2.3 and max displacement: 4.5

2020-09-25 21:09 UTC, colman-hartinger commented
Sorry I shoudl've realized this in your previous PR about the z-offset but the problem didn't click until I read "If the user moves the normal mesh, the modifier mesh should move with it "

2020-09-25 21:11 UTC, dougkenik commented
> > We cannot do that because the position of the meshes will get messed up on project open. What is the message from the back end?
> 
> It's not that you get an error from the backend its that the transformation gets messed up during validation. I didn't save the optimized job I just ran but I'll run another to post for example.
> 
> The problem is that the results will be vastly different from the optimized results. So if you take a part with a modifier mesh that you just got back from an optimization and then go back to validate it with the exact same loading and anchors you will get very different results when the modifier mesh is defined as a child of the printable node. In my test using a brake lever with a modifier mesh generated from an optimization the results were a fos: 1.6 and max displacement: 3.45 under the same loading and anchors in validation the results went up to fos: 2.3 and max displacement: 4.5

Ok, well it's likely because our 3MF reader is not recognizing the node is a child of the parent, and not applying the transformation correctly. We might want to consider updating our 3MF reader to handle this. I could see this just happening from other potential workflows. @bradymadams  - thoughts?

2020-09-25 21:35 UTC, bradymadams commented
Can someone provide me with an example 3MF that doesn't get processed correctly on the backend?

2020-09-25 21:50 UTC, colman-hartinger commented
@bradymadams here you go. 
[UMS5_simple_lever.zip](https://github.com/tetonsim/is-cura-ui/files/5285525/UMS5_simple_lever.zip)

2020-09-25 22:22 UTC, bradymadams commented
This probably isn't surprising, but in the 3MF in this case the mod mesh gets grouped as a component under the normal mesh. We don't currently read in the `component` tags, so in this case we would completely omit the mod mesh from the smart slice analysis. I created an issue to support this: https://github.com/tetonsim/py3mf/issues/2

```xml
        <resources>
                <object id="1" name="simple_lever.stl" type="model">
			<components>
				<component objectid="2" transform="1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0" />
			</components>
		</object>
		<object id="2" name="SmartSliceMeshModifier" type="model">
                    ...
		</object>
	</resources>
	<build>
		<item objectid="1" transform="1.0 0.0 0.0 0.0 0.0 1.0 0.0 -1.0 0.0 165.0 120.0 6.0" />
	</build>
```

2020-09-28 14:38 UTC, bradymadams commented
This PR should fix the problem with grouping the mod mesh: https://github.com/tetonsim/pywim/pull/69

2020-09-28 17:12 UTC, jake-kirkland-teton approved these changes

2020-09-28 19:07 UTC, colman-hartinger approved these changes
Just tested out and mod meshes are validating with same results as optimization

2020-09-28 21:33 UTC, bradymadams approved these changes

2020-09-28 21:33 UTC, merged