R20.2 api unittests
tetonsim/is-cura-ui pull request #341
Opened 2020-10-05 23:06 UTC by colman-hartinger

2020-10-05 23:22 UTC, colman-hartinger commented
More or less just a rough draft and some of the naming could obviously be better but everything is working so I'm opening this up for comments. 

I also think it could be useful to add pylint or a [codeQL](https://github.com/github/codeql-action) check to make more use of the automated tests but that should probably be split off into another ticket

2020-10-06 13:49 UTC, bradymadams requested changes
Looks like a pretty foundation to start with, guys. Just a handful of straight forward change requests.

The "DOCKERFILE" should be spelled "Dockerfile".

Let's rename "run_in_docker.sh" to something more descriptive of what it's doing, such as "run_unit_tests.sh"

It's hard to parse out our test logs from all of the info being dumped to stdout/stderr. Can we print a summary at the end of the run of our unit test results?

2020-10-06 13:49 UTC, bradymadams commented on .github/workflows/smartslice-test.yml
> +    - name: test 1
Rename to "Unit Tests" or something else more descriptive.

2020-10-06 13:49 UTC, bradymadams commented on run_in_docker.sh
> +git clone -b 4.6 --single-branch  https://github.com/Ultimaker/Cura.git
We will probably want to parameterize the branch name and use that as an argument into this script that we get from a [build matrix in the github action](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix).

Unnecessary extra space after the `--single-branch` argument.

2020-10-06 13:49 UTC, bradymadams commented on run_in_docker.sh
> +python3 -m pip install PyQt5==5.10  teton-3mf teton-pywim
Unnecessary extra space after the `PyQt` argument.

2020-10-06 13:49 UTC, bradymadams commented on .github/workflows/smartslice-test.yml
> +    container: tetonsim/smartslicetests
Should we use a specific tag here (and not `latest`) so that any updates to the image can be managed to not break old branch tests? It's probably not super important, but I can imagine scenarios where we're working on a new release but need to hot patch an old release and we might need to use different images between the two development paths.

2020-10-06 13:49 UTC, bradymadams commented on SmartSlicePlugin/tests/run.py
> +        # TODO use prog.result to take appropriate action based off the results
Can the `TODO` be removed?

2020-10-06 13:49 UTC, bradymadams commented on SmartSlicePlugin/tests/test_API.py
> +class MockJob():
The Mock classes are probably fine here for now, but eventually these will need to be pulled out to a location where they can be used across more TestCases. It should be obvious, I suppose, as you guys expand out the unit tests.

2020-10-06 13:49 UTC, bradymadams commented on SmartSlicePlugin/tests/test_API.py
> +    def test_00_check_token_create(self):
Let's remove the numbers from the test names. It will only cause a headache when you want to add a new test in the middle and now you have to change all of the test names.

2020-10-06 16:01 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/run.py
> +        # TODO use prog.result to take appropriate action based off the results
I think it's pretty safe to remove the TODO. Done.

2020-10-06 16:02 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_API.py
> +class MockJob():
I moved them to MockClasses.py, might as well move them early.

2020-10-06 16:02 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_API.py
> +    def test_00_check_token_create(self):
Done.

2020-10-06 16:14 UTC, bradymadams commented on SmartSlicePlugin/tests/test_API.py
> +class MockJob():
If it's alright with you guys I'd prefer to use a more standard Python naming approach under the tests module/classes. I think `mock.py` would suffice.

2020-10-06 16:16 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_API.py
> +class MockJob():
Works for me, I just wasn't aware of the standard python naming for tests. `mock.py` it is.

2020-10-06 20:54 UTC, colman-hartinger commented
@bradymadams  after talking on slack earlier I decided to move both Cura and Uranium into the docker image since it made more sense in my head to keep them there instead of to be constantly cloning. If we want to test against a different version then we can implement some github action matrix and build docker images for those versions as well

2020-10-06 21:06 UTC, bradymadams commented
> @bradymadams after talking on slack earlier I decided to move both Cura and Uranium into the docker image since it made more sense in my head to keep them there instead of constantly cloning. If we want to test against a different version then we can implement some github action matrix and build docker images for those versions as well

Does the cloning inside the GH action add very much overhead? If not, I think we should consider cloning inside of the action. The reason being it will automatically test us against the latest UM and Cura without us having to keep an eye on every change in those repos. Additionally we won't have to create new docker images to keep up with the UM and Cura changes.

2020-10-06 21:12 UTC, colman-hartinger commented
> Does the cloning inside the GH action add very much overhead? 

I would say it would ~10-20 seconds but that could be offset by a quicker initialization of the image due to less layers. I'll change things to clone within the action

2020-10-07 16:57 UTC, bradymadams requested changes
I think the Dockerfile and shell scripts need some cleaning up. Looks like there's some redundant logic between the two. Also, use consistent styling for environment variables - it's preferred to use brackets rather than no brackets:

```bash
${PREFERRED}
$NOT_PREFERRED
```

2020-10-07 16:57 UTC, bradymadams commented on .github/workflows/smartslice-test.yml
> +  build:
Should we rename this job to something more indicative of what it does? Maybe "unit-tests"?

2020-10-07 16:57 UTC, bradymadams commented on Dockerfile
> +RUN git clone -b $URANIUM_BRANCH --depth 1 https://github.com/Ultimaker/Uranium
This shouldn't be in the Dockerfile anymore, since this is done within the action, right?

2020-10-07 16:57 UTC, bradymadams commented on Dockerfile
> +WORKDIR $CURA_APP_DIR
I think you should only have to re-specify `WORKDIR` when it changes.

2020-10-07 16:57 UTC, bradymadams commented on Dockerfile
> +ENV PYTHONPATH=${PYTHONPATH}:$CURA_APP_DIR/Uranium
This is done in the shell scripts, right?

2020-10-07 16:57 UTC, bradymadams commented on SmartSlicePlugin/tests/test_API.py
> +class test_API(_SmartSliceTestCase):
Sorry I missed this the first time around, but let's rename the class using standard class name styling.

2020-10-07 16:57 UTC, bradymadams commented on SmartSlicePlugin/tests/run.py
> +        print("\n", file = sys.__stderr__)
Are the two line break prints leftover from debugging?

2020-10-07 19:35 UTC, bradymadams commented on SmartSlicePlugin/tests/test_API.py
> +class testAPI(_SmartSliceTestCase):
Let's use the standard naming for classes: https://google.github.io/styleguide/pyguide.html#316-naming

Also, you guys might want to think about how you'll want to name test case classes going forward since there will ultimately be dozens of them. Choosing a good naming strategy will help you keep them organized. Something to think about, let me know if you want my opinion.

2020-10-07 19:35 UTC, colman-hartinger commented on SmartSlicePlugin/tests/run.py
> +        print("\n", file = sys.__stderr__)
I tried removing the print statements and that caused a segmentation fault

2020-10-07 19:36 UTC, bradymadams commented on SmartSlicePlugin/tests/test_API.py
> +class testAPI(_SmartSliceTestCase):
Also, class names do not have to match the sub-module name. Again, keeping with Python standard naming conventions, module names shouldn't be camel case (testAPI), test_api would be preferred (test_API would be okay, IMO).

2020-10-07 19:37 UTC, bradymadams commented on SmartSlicePlugin/tests/run.py
> +        print("\n", file = sys.__stderr__)
That seems very strange that print statements would be required to avoid a seg fault. If that's actually the case there might be a bigger problem somewhere else.

2020-10-07 19:40 UTC, colman-hartinger commented on SmartSlicePlugin/tests/run.py
> +        print("\n", file = sys.__stderr__)
wait never mind the tests just passed without the print statements. Must've been some other error that came up when I was cleaning up some of the scripts

2020-10-07 20:31 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_API.py
> +class testAPI(_SmartSliceTestCase):
Alright, it is done.

2020-10-07 20:43 UTC, bradymadams commented
@colman-hartinger since the Dockerfile is now just a couple of commands built on top of the cura-build-environment image - is there any reason to maintain our own image? Could those last two commands be run in the action instead?

Also, do they have a Python 3.5 image? I think it would be best if we ran our unit tests against Python 3.5 since that's what they deploy Cura with.

```
FROM ultimaker/cura-build-environment:python3.7-debian-latest

RUN apt-get install -y mesa-utils xvfb
RUN python3 -m pip install PyQt5=5.10
```

2020-10-07 20:44 UTC, jake-kirkland-teton commented
I'm actually not sure how that got included in the gitignore, that was my bad.

2020-10-07 20:52 UTC, colman-hartinger commented
> Also, do they have a Python 3.5 image? I think it would be best if we ran our unit tests against Python 3.5 since that's what they deploy Cura with.
>

@bradymadams  It doesn't look like there is a Python 3.5 image dev environment image available. Now that the Dockerfile is only 3 lines we can get rid of it and just add the packages to the build script. It will add  ~ 10 seconds to the test  time but the action is running pretty fast so I don't see a problem with that

2020-10-07 20:56 UTC, bradymadams commented
> @bradymadams It doesn't look like there is a Python 3.5 image dev environment image available. Now that the Dockerfile is only 3 lines we can get rid of it and just add the packages to the build script. It will add ~ 10 seconds to the test time but the action is running pretty fast so I don't see a problem with that

:+1: I think the added 10 seconds is worth the trade-off for not having to manage our own docker image.

2020-10-08 14:08 UTC, bradymadams approved these changes

2020-10-08 14:08 UTC, bradymadams commented
Will merge pending approval from @jake-kirkland-teton and @dougkenik

2020-10-08 14:22 UTC, dougkenik approved these changes

2020-10-08 15:09 UTC, jake-kirkland-teton approved these changes

2020-10-08 15:35 UTC, merged