R20.2 296 190
tetonsim/is-cura-ui pull request #349
Opened 2020-10-12 19:45 UTC by jake-kirkland-teton

This adds a Cost column to the results table when the cost is not 0. Also removes unused code from SmartSliceJobHandler

Closes #296 and #190

2020-10-12 20:39 UTC, colman-hartinger requested changes
Everything seems to work and the two functions removed from SmartSliceJobHandler seemed to be unused beforehand so I couldn't find any problem with them being removed. 

I have one request going forward and this is something I am guilty of too, but I don't think we should be naming branches off of the ticket numbers.

2020-10-12 20:39 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/ResultTable.py
> +            self.tableState = "noCost"
The use of a private and public variable both named tableState seems confusing

2020-10-12 22:30 UTC, dougkenik requested changes
Pretty good. I would move the Cost column to the right of Print Time.

2020-10-12 22:55 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/ResultTable.py
> +                    return "{} {}".format(currency, round(value, 2))
It is pretty similar. They display all of theirs through QML, but they pull the cura/currency preference and then attach the cost to 2 decimals.

2020-10-12 22:56 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/ResultTable.py
> +        if self._resultsDict[0][ResultsTableHeader.Cost.value] != 0.0:
I can certainly do that. A negative wouldn't make sense, but I figured if they somehow got a negative cost in Cura it could be displayed since it might alert the user to a problem. I don't have a preference either way though.

2020-10-12 23:03 UTC, jake-kirkland-teton commented
Alright. Done.

2020-10-13 12:21 UTC, dougkenik approved these changes

2020-10-13 13:26 UTC, bradymadams approved these changes

2020-10-13 15:15 UTC, colman-hartinger approved these changes

2020-10-13 15:35 UTC, merged