R20.2 custom messaging
tetonsim/is-cura-ui pull request #353
Opened 2020-10-29 17:51 UTC by jake-kirkland-teton

Alright guys, this isn't perfect, but it is a foundation to improve upon and it allows us to have control over our messages. There will still need to be functionality added as we move forward, but now we have the ability to display messages in the center of the screen, with a theme font of our choosing, with the possibility of centered buttons.

I'm sure there will be some changes to make. Let me know what you guys think.

Closes #343

2020-10-29 22:01 UTC, dougkenik requested changes

2020-10-29 22:01 UTC, dougkenik commented on SmartSlicePlugin/stage/ui/SmartSliceMessage.qml
> +            {
Lots of style things in this file. In general, we always put the open bracket on the same line as the item - `Button {`

2020-10-29 22:01 UTC, dougkenik commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +        from .ui.SmartSliceMessageExtension import SmartSliceMessage
What is this for?

2020-10-29 22:05 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +        from .ui.SmartSliceMessageExtension import SmartSliceMessage
These are only there to demonstrate the messaging system with test messages. They will be removed before the final merge.

2020-10-29 22:06 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessage.qml
> +            {
Fair. This is a copy of the MessageStack.qml, with additional functionality put in for our messages. I can go through it and adjust the styling.

2020-10-29 22:13 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +    def setLifetimeTimer(self, timer: QTimer) -> None:
I had a hard time getting the timers working, and this was part of my original fix to the problem. My fault, I meant to clean these up and forgot them. You are correct, we do not need a few of these.

2020-10-29 22:18 UTC, dougkenik commented
I also think there should be a way to inherit Message.qml and override what you need to. Have you searched for QML inheritance at all?

2020-10-29 22:22 UTC, jake-kirkland-teton commented
I did indeed do some research, but I may not have done a very good job. I can spend some more time looking into it.

2020-10-29 22:25 UTC, dougkenik commented
> I did indeed do some research, but I may not have done a very good job. I can spend some more time looking into it.

I think you might be able to use Message.qml in your object, and then modify properties of that - I don't know the details though:

https://stackoverflow.com/questions/11111785/does-qml-support-state-inheritance-overriding

2020-10-30 16:26 UTC, colman-hartinger requested changes
couple comments, Also all the qml should be styled according to google js style guide mainly all the semi-colons missing

2020-10-30 16:26 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +
Does using the same signal name  UM cause any problems?

2020-10-30 16:26 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +                         option_text=ssm_option_text, option_state=ssm_option_state)
possibly break these functions parameters up they're a little hard to read

2020-10-30 16:26 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/SmartSliceMessage.qml
> +                        {
maybe use the SmartSliceActionButtonStyle here instead of ints. also in javascript you want to use === for comparisons although for this case it shouldn't make a difference

2020-10-30 16:26 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/SmartSliceMessage.qml
> +                        if (alignPosition == 1)
unused comment

2020-10-30 16:26 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +        """Add an action to the message
use multi line function declaration

2020-10-30 16:26 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +    FontRole = Qt.UserRole + 15
what is the + 15 for?

2020-10-30 16:26 UTC, colman-hartinger commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +        for index in range(0,len(self.items)):
you don't need the 0 in for the range

2020-10-30 16:29 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +
Not that I have found.

2020-10-30 16:35 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +    FontRole = Qt.UserRole + 15
The role is added to the other roles from the VisibleMessagesModel that it is overriding, and they number to 14. We could change that number to one farther out to give them more space to add roles later if we choose.

2020-10-30 16:43 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +        """Add an action to the message
Done.

2020-10-30 16:43 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessage.qml
> +                        if (alignPosition == 1)
Fair. Cleared it.

2020-10-30 16:45 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessage.qml
> +                        {
I will look into using the ActionButtonStyle, I have some changes to attempt in the QML at this point already.

2020-10-30 16:45 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +                         option_text=ssm_option_text, option_state=ssm_option_state)
I tried to reorganize them and added a new line

2020-11-02 14:59 UTC, bradymadams commented
The rendering isn't super clean on my machine. Anyone else see this?

![image](https://user-images.githubusercontent.com/23110600/97882806-4376a380-1ce1-11eb-83c4-49e847d3c1ca.png)

2020-11-02 16:39 UTC, bradymadams requested changes
I know you're working on some other changes right now, so this isn't an in depth review. Just a few surface things that I noticed. 

1. The "SS" abbreviations isn't really typical for naming in our repo. I know spelling out "SmartSlice" makes those names verbose, but it's more consistent with how we name our variables, etc.

2. The location of `ss_messages` and `visible_ss_messages` seems off to me. They are entirely managed in `SmartSliceMessageModel`, so it seems like they'd be more appropriately located within that class. Is there a reason why you need to put them in the `SmartSliceStage` class?

2020-11-02 16:39 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +    def createActionsModel(self, actions):
The implementation of this function looks identical to the parent implementation. Is it necessary to override it?

2020-11-02 16:44 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMain.qml
> +    Last Modified October 29, 2020
Deal. Removed.

2020-11-02 16:53 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +        self._inactivity_timer = None  # type: Optional[QTimer]
You are absolutely correct. I had a really hard time getting the timers and some of the functionality working at first, and I made a lot of changes and I was under the assumption that I needed all of the changes I made, but as I pare them down, a lot of these were unneeded. I have removed most of these.

2020-11-02 16:57 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +        self.appendItem({"font": message.getFont()})
No, the signals do not actually need redefined, I have those removed.

Hmm... it does not appear that it does. I was building on the way that Cura does it, assuming it was needed at some point, but the font role still functions as expected without. I'll remove it.

2020-11-02 17:00 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +    def createActionsModel(self, actions):
It is indeed. And no, I no longer think it is needed to override it at this point. I have removed it.

2020-11-02 17:48 UTC, jake-kirkland-teton commented
So I think overall I got a little frustrated with this and my understanding of how some of it worked. Through the requested changes and working on this a bit more, I feel like I have a bit better of a handle on it now. I appreciate you guys helping me out on this one and I apologize that it needed so much adjusting. Thanks for the patience with me as well.

@dougkenik: I have tried quite a few different methods to override the MessageStack.qml, and I have been unable to access some of the nested items that we want to adjust, such as the font/label for the messages, changing the close button action, or adding the additional action button setup for centered buttons. Do you have any ideas on how to access those objects? I have tried accessing them through encapsulation, through using dot chains, overriding the entire item structure, etc. Not having any luck on that front.

@bradymadams: On the `visible_messages` and `visible_smartslice_messages` front, I may be doing something incorrectly or not understanding properly, but the `SmartSliceMessageModel` is created AFTER the messages are attempted to be shown, which doesn't allow me to access the lists that are created in the Model, for the first messages. So I was accessing the instance of the Stage since it is created and it is a central location that I can actually get the created instance of to add and remove messages from the lists.

I worked on the formatting of the QML file overall, though it probably still needs a little work. One question on that, were we putting semicolons at the end of ALL statement lines? Or just returns and functions?

2020-11-02 18:12 UTC, dougkenik commented
> So I think overall I got a little frustrated with this and my understanding of how some of it worked. Through the requested changes and working on this a bit more, I feel like I have a bit better of a handle on it now. I appreciate you guys helping me out on this one and I apologize that it needed so much adjusting. Thanks for the patience with me as well.
> 
> @dougkenik: I have tried quite a few different methods to override the MessageStack.qml, and I have been unable to access some of the nested items that we want to adjust, such as the font/label for the messages, changing the close button action, or adding the additional action button setup for centered buttons. Do you have any ideas on how to access those objects? I have tried accessing them through encapsulation, through using dot chains, overriding the entire item structure, etc. Not having any luck on that front.
> 
> @bradymadams: On the `visible_messages` and `visible_smartslice_messages` front, I may be doing something incorrectly or not understanding properly, but the `SmartSliceMessageModel` is created AFTER the messages are attempted to be shown, which doesn't allow me to access the lists that are created in the Model, for the first messages. So I was accessing the instance of the Stage since it is created and it is a central location that I can actually get the created instance of to add and remove messages from the lists.
> 
> I worked on the formatting of the QML file overall, though it probably still needs a little work. One question on that, were we putting semicolons at the end of ALL statement lines? Or just returns and functions?

I don't know how to access the items. There should be a way to override a QML class, but UM might not have set it up that way.

2020-11-02 18:29 UTC, bradymadams commented
> @bradymadams: On the `visible_messages` and `visible_smartslice_messages` front, I may be doing something incorrectly or not understanding properly, but the `SmartSliceMessageModel` is created AFTER the messages are attempted to be shown, which doesn't allow me to access the lists that are created in the Model, for the first messages. So I was accessing the instance of the Stage since it is created and it is a central location that I can actually get the created instance of to add and remove messages from the lists.

Okay, I think I understand. And I see that your implementation is consistent with UM's implementation, which stores the messages in the Application instance. From a design perspective, it definitely breaks encapsulation, so it's not ideal. I'm not saying we should change it, it's probably fine as it is, especially since we're mocking Cura's message system.

2020-11-02 18:34 UTC, jake-kirkland-teton commented
@dougkenik Alright. The only things I have found are alias's and signals, but UM doesn't have them setup in their MessageStack. And I agree that it's a lot of code duplication, which I'm not a fan of either, but I don't see another way to get around it with the way things are currently. 

@bradymadams I agree it's not optimal. I will leave it as is and if we determine a better way to handle it down the road, we can always attempt that later.

2020-11-02 21:08 UTC, jake-kirkland-teton commented
I think this is ready for a second look over. I attempted to use a global to check against for the button alignment, but it doesn't load at the right time and causes a bizarre issue where it checks against undefined.

And @bradymadams  I do get the rendering issues at times, but it's the same issue that appears when the window is just the right size. The text rendering is already NativeRendering, so I am honestly not sure what to do to prevent that issue.

2020-11-03 14:06 UTC, dougkenik reviewed
The text looks fine for me. I think the confirmation button needs to be blue, and the cancel / others can be grey - same styles as the validate button we have (minus the highlight).

2020-11-03 15:41 UTC, bradymadams requested changes

2020-11-03 15:41 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +        """Add an action to the message
After the first line the lines should only be indented one level and the closing parenthesis should be on it's own line aligned with the initial line:

```python
def foo(
    x: int,
    s: str
):
    # foo logic

2020-11-03 15:41 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +                              "button_style": button_style, "button_align": button_align})
Is there any difference between this statement and the one performed in the parent `addAction`? If not, just call the parent function.

2020-11-03 15:41 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +    FontRole = Qt.UserRole + 15
We should probably do that, if possible. It would suck if Cura released an update with an added role and that was the only thing that broke our plug-in compatibility. If possible, I'd recommend we add a large number, like 100.

2020-11-03 15:41 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +        self.removeSmartSliceMessage(message_id)
Is `hideSmartSliceMessage` necessary since it's just a thin proxy for `removeSmartSliceMessage`?

2020-11-03 15:41 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +        SECONDARY = 2
Since we're not adding anything to this enum that doesn't exist in the `Message.ActionButtonStyle` I'd say we just omit this.

2020-11-03 15:41 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +    class SmartSliceActionButtonAlignment:
Can you look into deriving this from `Message.ActionButtonAlignment` and just adding the `ALIGN_CENTER`. If you do that, I think you could completely omit the implementation of `addAction` in `SmartSliceMessage`.

2020-11-03 16:43 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +        self.removeSmartSliceMessage(message_id)
Good point. I do not believe it actually is, I think our signals work a bit differently than the ones for the normal messages so we shouldn't need it. I removed it.

2020-11-03 16:43 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +        SECONDARY = 2
Done.

2020-11-03 17:04 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +                              "button_style": button_style, "button_align": button_align})
I actually think it works without overriding it. I was under the impression that it was going to be necessary but you are right, it isn't.

2020-11-03 17:25 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +    class SmartSliceActionButtonAlignment:
I can just change this so only ALIGN_CENTER is in this class, and rename it ActionButtonAlignment, which will allow us to just call `SmartSliceMessage.ActionButtonAlignment.ALIGN_CENTER` or `Message.ActionButtonAlignment.ALIGN_LEFT/RIGHT`.

If we don't want to have UM.Message imported in these situations as well, we can always just have all three of them defined in the `SmartSliceMessage` `ActionButtonAlignment` too.

2020-11-03 18:28 UTC, jake-kirkland-teton commented
Alright, we are now using `Cura.PrimaryButton` and `Cura.SecondaryButton` for the buttons and I have made the requested changes Brady. If you feel like we should add all of the Alignment types to our class, I can do that as well, it depends on how we want to do it.

2020-11-03 18:39 UTC, bradymadams requested changes
Looks good. Just one last final request. If the Doug and Colman think it looks good as well let's remove the test code and prep it for merge.

2020-11-03 18:40 UTC, bradymadams requested changes
Sorry, forgot to submit the change request comment on my last review. Here it is.

2020-11-03 18:40 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +    class ActionButtonAlignment:
Let's derive this from `Message.ActionButtonAlignment` so that it picks up the other alignment properties.

2020-11-03 18:47 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceMessageExtension.py
> +    class ActionButtonAlignment:
I am not sure why I didn't fully understand that request the first time you requested it. Sorry Brady. Got it fixed.

2020-11-03 18:53 UTC, dougkenik approved these changes
Buttons look good

2020-11-03 19:04 UTC, bradymadams approved these changes

2020-11-03 19:05 UTC, colman-hartinger requested changes
Code looks good, sometimes after deleting a message the text rendering for the other messages gets a little funky like in Brady's photo but that doesn't seem like a real problem. The tests messages in smart slice stage should be removed before merging into r20.2

2020-11-03 19:05 UTC, colman-hartinger commented on packaging/package.json
> +    "package_version": "20.2.7",
is there a version r20.2.6?

2020-11-03 19:08 UTC, colman-hartinger commented on packaging/package.json
> +    "package_version": "20.2.7",
ignore that I guess the package.json version was off by one

2020-11-03 20:16 UTC, colman-hartinger approved these changes

2020-11-03 20:18 UTC, merged