Changed the message for connection issues
tetonsim/is-cura-ui pull request #354
Opened 2020-11-05 22:55 UTC by jake-kirkland-teton

Added more text and a link to the help page.
Additionally, fixed a bug with the new messages system.

Had a little trouble with this one getting the hover hand working correctly, and discovered a bug with the messaging system that I'm honestly not sure how it was working at all without. Should be good to go now.

Closes #352

2020-11-05 23:10 UTC, dougkenik requested changes
A few comments in the picture below on my machine:

- "Servers" should not be capitalized. Add an Exclamation point at the end
- I am seeing text wrapped in <href>. We need to get rid of that, and.... we need to have the link open the user's email client addressed to help@tetonsim.com, with a prepopulated title "Smart Slice Cannot Connect Error" A reference of this is in Extensions->Smart Slice->Contact (I think I gave you the wrong link last time)



![Untitled](https://user-images.githubusercontent.com/24813209/98306608-062c4300-1f79-11eb-8687-a3a113e7a440.png)

2020-11-06 14:31 UTC, bradymadams requested changes
Doug already mentioned the major items. I just have one style change request.

2020-11-06 14:31 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +        self._error_message = SmartSliceMessage(smartslice_lifetime= 180)
Styling - no spaces around `=` on named argument assignments.

2020-11-09 18:16 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +        self._error_message = SmartSliceMessage(smartslice_lifetime= 180)
Got it, good catch.

2020-11-09 18:21 UTC, jake-kirkland-teton commented
Alright, check again for me. I'm not sure why the inline worked for me and not you Doug. 

About the text wrapping, does it look ok now that the link is hopefully fixed?

And ahhh. No worries. I got it changed to a mailto.

2020-11-09 19:31 UTC, dougkenik requested changes
Still not displaying correctly. Let's also remove the comma between "connection, and are still"

![image](https://user-images.githubusercontent.com/24813209/98587510-1a28bb00-227f-11eb-8145-9798e7d3e5ed.png)

2020-11-10 17:36 UTC, jake-kirkland-teton commented
OK. Please check again and make sure it is appearing correctly for you guys, but I think that should do it.

2020-11-10 18:32 UTC, bradymadams approved these changes

2020-11-10 18:32 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +        self._error_message = SmartSliceMessage(smartslice_lifetime= 180)
Looks like this still needs to be fixed.

2020-11-10 18:35 UTC, jake-kirkland-teton commented
Not sure how that one got lost, but my fault. Got it for sure now.

2020-11-10 19:41 UTC, dougkenik approved these changes

2020-11-10 20:34 UTC, merged