Results Buttons
tetonsim/is-cura-ui pull request #355
Opened 2020-11-12 23:06 UTC by jake-kirkland-teton

Added new buttons for prepping new results system and additional messages.

Let me know of the opacity needs changed.

Closes #342

2020-11-13 18:48 UTC, dougkenik requested changes
Functionality looks good - just the comments

2020-11-13 18:54 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceResultsButtons.qml
> +            UM.SimpleButton {
Ah yeah I had meant to put a hover color on these and spaced it. I will do that. Will less opaque work for that?

And this basically is a recolor button. This uses a RecolorImage as the icon and adds button functionality.

2020-11-13 23:09 UTC, dougkenik approved these changes
You did a very nice job with this. Looks great

2020-11-13 23:09 UTC, dougkenik commented on SmartSlicePlugin/stage/ui/SmartSliceResultsButtons.qml
> +    border.width: UM.Theme.getSize("default_lining").width
Let's also use the {} with border

2020-11-13 23:17 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/ui/SmartSliceResultsButtons.qml
> +    border.width: UM.Theme.getSize("default_lining").width
Ah good call. And thanks!

2020-11-16 13:47 UTC, bradymadams approved these changes
Looks good :+1:

2020-11-16 13:48 UTC, merged