R20.2 problem meshes
tetonsim/is-cura-ui pull request #364
Opened 2020-12-10 18:07 UTC by jake-kirkland-teton

This adds the new problem meshes and a system to remove them so they don't interfere with other operations. 

I currently have the server set to Test since without the mesh data the new changes fail. 

Closes #345

2020-12-11 13:56 UTC, dougkenik requested changes
From a UX standpoint, when a user has selected one of the results buttons (displacement or fos), leaves the stage, and then comes back, the meshes will still be present, but the message is not there, and the button is deselected. I think we should retain the selected button, meshes, and message.

Also, when viewing a problem mesh, I would suggest we also make the part more transparent, so we can see inside of it

2020-12-11 13:56 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +            self._proxy.clearProblemMeshes()
Why do you need to clear problem meshes here, and not after a validation? What if a user ran multiple validations?

2020-12-11 17:00 UTC, bradymadams commented
@jake-kirkland-teton any plans to add unit tests for this functionality?

2020-12-11 17:26 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +            self._proxy.clearProblemMeshes()
Good catch. I thought it was covered by the other clears, but I think there are a couple edge cases I didn't fully think through I need to account for.

I can certainly make the popup reappear, that shouldn't be a problem.

I will see what I can do to make the part transparent.

2020-12-11 17:27 UTC, jake-kirkland-teton commented
@bradymadams I have been thinking about getting myself into the habit of writing some unittests when I finish a ticket. I think this would be a reasonable place to start that. I will write some unittests for this system, either for this ticket, or after the displacement is added, whichever seems smarter.

2020-12-11 17:32 UTC, bradymadams commented
> @bradymadams I have been thinking about getting myself into the habit of writing some unittests when I finish a ticket. I think this would be a reasonable place to start that. I will write some unittests for this system, either for this ticket, or after the displacement is added, whichever seems smarter.

My opinion is to add the unit tests along with the functionality, in the same PR. This is what we do in our solver repos and it works really well.

2020-12-14 19:46 UTC, colman-hartinger approved these changes
All the code looks good to me. Running some tests in smartslice to test the ui

2020-12-14 22:42 UTC, bradymadams requested changes
Nice job, the code looks good and clean. A few minor requests.

2020-12-14 22:42 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceView.py
> +                    elif node.callDecoration("isNonPrintingMesh") and node.hasDecoration("is_problem_area"):
I'm not sure how efficient the node decorators are and since this logic is in the rendering loop it gets called a lot. I would pull the decorator calls outside of the if statements and store them in variables so they only get called once.

2020-12-14 22:42 UTC, bradymadams commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +        if proxy.hasProblemMeshesVisible == True:
`if proxy.hasProblemMeshesVisible:` is preferred.
https://google.github.io/styleguide/pyguide.html#214-truefalse-evaluations

2020-12-14 22:42 UTC, bradymadams commented on SmartSlicePlugin/utils/__init__.py
> +def buildMesh(mesh, title):
Let's add type annotations here so it's more clear what arguments it takes and what it returns.

2020-12-14 22:42 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +        pass
Looks like a leftover `pass`?

2020-12-14 23:03 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +        if proxy.hasProblemMeshesVisible == True:
Touche. That is on me. Got it changed.

2020-12-14 23:33 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +        pass
Yeah, it is. I forgot to remove that.

2020-12-14 23:33 UTC, jake-kirkland-teton commented on SmartSlicePlugin/utils/__init__.py
> +def buildMesh(mesh, title):
Can do.

2020-12-15 00:09 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceView.py
> +                    elif node.callDecoration("isNonPrintingMesh") and node.hasDecoration("is_problem_area"):
Very good point. Got that taken care of.

2020-12-15 00:18 UTC, jake-kirkland-teton commented
Alright, so this contains many of the requested changes, and the UX should be fixed now. It is good to go for some more testing. 

There is one last change that @dougkenik and I talked about, and it is to move the building of the meshes into their own class. That way the problem meshes and the mod meshes will be something like a `SmartSliceSceneNode` and we will be able to customize them at will.
 
Once that is done, I will be setting up the unittests for this as well.

2020-12-15 18:43 UTC, dougkenik commented
The functionality is better, except for one question....

What happens if I open a validation or optimization which was saved from a previous version of the back-end?

2020-12-15 18:51 UTC, jake-kirkland-teton commented
Hmmm, I am honestly not sure. I will have to look into that.

2020-12-15 19:59 UTC, bradymadams requested changes
I think the view class could use a little more tidying up.

On second look are we adding/removing the problem meshes rather than building them once and then just showing/hiding them? Is there a reason the current approach is preferred?

2020-12-15 19:59 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceView.py
> +            is_problem_area = node.hasDecoration("is_problem_area")
Probably doesn't make sense to call these unless line 61 is true, right?
Two of them could go under the if statement on line 62.

2020-12-15 19:59 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceView.py
> +                                renderer.queueNode(node, shader = self._shader, uniforms = uniforms)
No whitespace around `=` on argument assignments. I know you were just using the style that was already in this file, but the general rule is when modifying existing code let's improve the style, if necessary.

https://google.github.io/styleguide/pyguide.html#36-whitespace

2020-12-15 19:59 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceView.py
> +                        has_problem_area = True
I don't think this is necessary since it's set in the for loop on line 42.

2020-12-15 19:59 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceView.py
> +                                renderer.queueNode(node, shader = self._shader, uniforms = uniforms, transparent = True)
I think this could be condensed to one call to `queueNode` using `transparent=has_problem_area`.

2020-12-15 20:37 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceView.py
> +            is_problem_area = node.hasDecoration("is_problem_area")
Hmm. Good point. I moved is non printing and is problem area.

2020-12-15 20:37 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceView.py
> +                        has_problem_area = True
Ah, yes. Good catch. I meant to remove that one.

2020-12-15 20:38 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceView.py
> +                                renderer.queueNode(node, shader = self._shader, uniforms = uniforms, transparent = True)
Ohhhh. I like that.

2020-12-15 20:39 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceView.py
> +                                renderer.queueNode(node, shader = self._shader, uniforms = uniforms)
Fixed

2020-12-22 18:30 UTC, jake-kirkland-teton commented
One last comment, is that we no longer need the `SmartSliceDecorators` with this change. I did not yet remove the file, but if we are all ok with that I can remove it before we merge these changes.

2020-12-22 18:42 UTC, bradymadams commented
> One last comment, is that we no longer need the `SmartSliceDecorators` with this change. I did not yet remove the file, but if we are all ok with that I can remove it before we merge these changes.

I am always in favor of removing unused/unnecessary code. It will always be in the git history if we ever need to resurrect it.

2020-12-22 18:52 UTC, dougkenik reviewed
So those decorators did a lot for tracking added / removed meshes and identifying Z-Offsets. Have you tested all of that?

2020-12-22 18:54 UTC, jake-kirkland-teton commented
@dougkenik I believe I have. There is a replacement added/removed system now and the Z-Offsets are a Cura Decorator that is still implemented. It would be good to get someone to double check and ensure I haven't unknowingly broken something, but I think everything is still tracked properly.

2020-12-23 15:10 UTC, dougkenik requested changes
This has come a long way Jake!

2020-12-23 15:10 UTC, dougkenik commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +    def mesh_type(self):
It might be easier just to expose 'self._mesh_type' as 'self.mesh_type' and forgo the properties?

2020-12-23 15:10 UTC, dougkenik commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +    def is_removed(self):
Same here. The properties don't make a whole bunch of sense to me

2020-12-23 16:04 UTC, dougkenik requested changes
Also, when I try to open the attached 3MF, I get a crash (traceback below):

2020-12-23 09:00:48,679 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2020-12-23 09:00:48,684 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2020-12-23 09:00:48,687 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "X:\4.6-exe\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 1013, in event
2020-12-23 09:00:48,691 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "X:\4.6-exe\build\inst\lib\python3.5\site-packages\UM\Qt\QtApplication.py", line 464, in event
2020-12-23 09:00:48,694 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "X:\4.6-exe\build\inst\lib\python3.5\site-packages\UM\Event.py", line 218, in call
2020-12-23 09:00:48,698 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "X:\4.6-exe\build\inst\lib\python3.5\site-packages\UM\Signal.py", line 332, in __performEmit
2020-12-23 09:00:48,701 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "C:\Users\DougKenik\AppData\Roaming\cura\4.6\plugins\SmartSlicePlugin\stage\SmartSliceScene.py", line 516, in _process_mesh_analysis
2020-12-23 09:00:48,704 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     job.callback()
2020-12-23 09:00:48,707 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "C:\Users\DougKenik\AppData\Roaming\cura\4.6\plugins\SmartSlicePlugin\SmartSliceExtension.py", line 300, in afterSmartSliceNodeInit
2020-12-23 09:00:48,710 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.proxy.problem_area_results = results.fea_results.steps[0].increments[0].model_results.problem_regions
2020-12-23 09:00:48,712 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "C:\Users\DougKenik\AppData\Roaming\cura\4.6\plugins\SmartSlicePlugin\3rd-party\cpython-common\pywim\__init__.py", line 99, in __getitem__
2020-12-23 09:00:48,715 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     return super().__getitem__(key)
2020-12-23 09:00:48,718 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: IndexError: list index out of range
2020-12-23 09:00:48,855 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [63]: Updating QualityProfilesDropDownMenuModel.
2020-12-23 09:00:48,862 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [34]: Updating CustomQualityProfilesDropDownMenuModel.
2020-12-23 09:00:50,627 - INFO - [MainThread] cura.Machines.MachineErrorChecker._setResult [187]: Error check finished, result = False, time = 3.1s
2020-12-23 09:00:56,609 - DEBUG - [MainThread] cura.AutoSave._onTimeout [60]: Autosaving preferences, instances and profiles
[webinar_validation.zip](https://github.com/tetonsim/is-cura-ui/files/5736071/webinar_validation.zip)

2020-12-23 16:22 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +                mesh.setVisible = True
Ah, you are absolutely correct.

2020-12-23 16:27 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceExtension.py
> +        self._outputManager._output_devices["local_file"].writeSuccess.connect(self.readd_meshes)
Yup. That is my bad on the naming front. Got it fixed.

2020-12-23 16:33 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +    def mesh_type(self):
Sure. I will certainly do that instead. I did a little research into it since I honestly wasn't super sure on when to and when not to use properties and you are correct, they don't really offer much benefit in this circumstance.

2020-12-23 17:59 UTC, jake-kirkland-teton commented
Alright, this should be fixed now! I also moved the SmartSliceMessages per @dougkenik 's request.

2020-12-23 20:02 UTC, bradymadams requested changes
The unit tests seem pretty lacking to me. It seems like they're just creating objects and then checking a few attributes on them. I'd like to see some tests that get more code coverage on the new code.

2020-12-23 21:57 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +    def __init__(self, mesh_type: MeshType = MeshType.Normal, mesh: 'pywim.chop.mesh.Mesh' = pywim.chop.mesh.Mesh(), title: str = "NormalMesh"):
Alright. That sounds good. I would like a run down on why, just so I know, but no rush.

2020-12-23 21:58 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +            }
Gotcha. Fixed.

2020-12-23 21:59 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        pass
I have removed them.

2020-12-23 22:35 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +        return self
I am not totally sure what I was thinking. I will make that into it's own variable that is returned rather than self.

2020-12-23 22:40 UTC, bradymadams commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +        return self
If you do that, that implies this function should be creating a new SmartSliceMeshNode. Are you sure that's what you want?

2020-12-23 22:55 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +        if problem_mesh_data is not None:
No it does not. It was a hold over from a different way I was building the meshes. I have removed it.

2020-12-23 23:06 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +            proxy.results_buttons_popup_visible = True
It is necessary. `closeResultsButtonPopup` does in fact set it to False. I thought it would be more efficient to just reuse the proxy variable so the popup can automatically come back up when you swap back to the tab, rather than writing a new method to handle it.

2020-12-24 00:28 UTC, jake-kirkland-teton commented
Alright, so I have made a fair amount of changes. There are still a couple things to be done when I return:

1) Figure out the parent for the `SmartSliceMeshNode` class. I tried a couple things but was unsucessful.
2) Test the changes to the unittests and then build some new more effective ones and work with Brady to make that happen.

2021-01-04 20:51 UTC, jake-kirkland-teton commented
OK. After some more research and testing, I have found that there is no need to pass in a constructed scene node as the parent. The ONLY reason a parent is passed into the UM SceneNode constructor is to do an automatic `.addChild` to that parent on construction, and our nodes will always be added to the parent of our choosing after creation anyway.
Additionally, I was unable to get the `SmartSliceSceneNode` constructor to work correctly directly passing the node we want as the parent in, because of some signal emitting issues on inheriting the other `init`s, so I believe the way it is being constructed and attached to it's desired parent with this last commit is the correct way to handle it, unless I have missed something.

2021-01-04 21:36 UTC, bradymadams commented
> Additionally, I was unable to get the `SmartSliceSceneNode` constructor to work correctly directly passing the node we want as the parent in, because of some signal emitting issues on inheriting the other `init`s, so I believe the way it is being constructed and attached to it's desired parent with this last commit is the correct way to handle it, unless I have missed something.

So that means the problem meshes don't have a parent, right? It feels more appropriate if their parent was the smart slice scene root or the printable node they are related to.

2021-01-04 21:38 UTC, jake-kirkland-teton commented
Actually it just means they aren't assigned a parent within the constructor for the object. When they are added to the scene they are added as a child to the `only_printable_node`, which then becomes their parent.

2021-01-06 16:01 UTC, bradymadams commented
@jake-kirkland-teton are you ready for another round of reviews on this or are you still working on unit tests?

2021-01-06 16:08 UTC, jake-kirkland-teton commented
I am indeed working on better unittests. Though unless that is absolutely critical to the release, I would suggest that we continue with the reviews and keep getting the features in so it can get to a point where the team can start testing it. I will keep working on tests and bugfixes and the displacement stuff as we move forward.

2021-01-06 16:20 UTC, bradymadams commented
Is your suggestion that we move forward to merge this without better unit tests?

2021-01-06 16:22 UTC, jake-kirkland-teton commented
If that is acceptable, yes. If the consensus is to wait until I complete better tests, we can do that as well. I just don't want to be holding the testing of the release up.

2021-01-06 16:33 UTC, bradymadams commented
> If that is acceptable, yes. If the consensus is to wait until I complete better tests, we can do that as well. I just don't want to be holding the testing of the release up.

I'd prefer we add good unit tests along with the functionality in each PR. We've been dragging our feet for too long on writing more unit tests in the plug-in - we need to start making it a standard part of the development process.

2021-01-06 16:57 UTC, bradymadams requested changes
Looking better. A few items I noticed. I'll review again once there's updates to the unit tests.

2021-01-06 16:57 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +            meshes_to_show = ("high_strain")
This is just setting a string, but it looks like you actually want a tuple. One item tuples need a comma.

2021-01-06 16:57 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +            if len(problem_meshes) > 0:
Is this redundant with the check on line 849?

2021-01-06 16:57 UTC, bradymadams commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +                    settings.addInstance(new_instance)
Looks like the above functionality is very similar to that in SmartSliceCloudProxy.py: https://github.com/tetonsim/is-cura-ui/pull/364/files#diff-bcd48d4cb072bf3a670395eadeb84f6f25ffa67ea5ba92f37d99ba158d0a5313L942

This logic is complicated enough that my first reaction is that it should be consolidated. Thoughts?

2021-01-08 23:56 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +            meshes_to_show = ("high_strain")
Ah yes, you are correct. Fixed.

2021-01-08 23:57 UTC, jake-kirkland-teton commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +            if len(problem_meshes) > 0:
I think I was just being extra cautious. I don't think we need the second check. Removed.

2021-01-08 23:58 UTC, jake-kirkland-teton commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +                    settings.addInstance(new_instance)
Now that I am comfortable with the tests, I will look into this a little more. I think it might be able to be consolidated. They are very similar, I just need to try to move them somewhere accessible and try to generalize it so it can be used in both cases.

2021-01-11 18:32 UTC, bradymadams requested changes
The unit tests look much better.

2021-01-11 18:32 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +            if len(problem_meshes) > 0:
The check is still there in the PR. Maybe you have a commit you haven't pushed yet?

2021-01-11 18:32 UTC, bradymadams commented on SmartSlicePlugin/tests/mock.py
> +        cube.addCube(1,1,1)
spaces between arguments

2021-01-11 18:32 UTC, bradymadams commented on SmartSlicePlugin/tests/mock.py
> +        pass
"pass" not necessary here

2021-01-11 18:32 UTC, bradymadams commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        self.assertNotEqual(our_mesh, [])
If we expect a certain number of meshes in the returned list then I think it would be better to assert the length of the list.

2021-01-11 18:32 UTC, bradymadams commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        mesh_data[0].name = "high_strain"
The above few lines are duplicated a few times in this class - I'd recommend consolidating into a simple static method.

2021-01-11 18:32 UTC, bradymadams commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        new_node = MockModel()
It doesn't look like this is used anywhere. If not, is the `MockModel` class needed?

2021-01-11 18:35 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/mock.py
> +        cube.addCube(1,1,1)
Yeah, it's on my current commit that I haven't pushed yet.

Gotcha, I meant to go back and clean up the formatting a little and forgot.

2021-01-11 18:36 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/mock.py
> +        pass
Another place I didn't clean up. I was using the pass to debug.

2021-01-11 18:36 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        self.assertNotEqual(our_mesh, [])
Ah fair enough. I think that is a good point, that makes it easy to modify once the deflection meshes are in too.

2021-01-11 18:37 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        mesh_data[0].name = "high_strain"
Touche. I will do that.

2021-01-11 18:38 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        new_node = MockModel()
The model is not technically used directly, but the `MockModel` class builds a model for the build plate to emulate a loaded stl. I suppose I could just call MockModel rather than assign it to a variable if that would be cleaner.

2021-01-11 18:46 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        new_node = MockModel()
And actually, the method doesn't return anything, so I should just be calling it anyway.

2021-01-11 19:18 UTC, bradymadams commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        new_node = MockModel()
Well MockModel is a class, not a method, so it does return an object of `MockModel`. But if the only use of it is the side effects that occur from the logic in the constructor then it might be cleaner to just move it to a free function, or a static method in the test class.

2021-01-11 20:29 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        new_node = MockModel()
Alright. That is a good point. I was thinking of keeping it available to other future tests, but that is a good point, I think we could add it to the `_SmartSliceTestCase` class as a method.

2021-01-11 20:34 UTC, bradymadams commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +        new_node = MockModel()
This doesn't need to be done in this PR, but something you might think about is how to design a system that will let you easily and consistently setup the state of Cura for unit tests. You can imagine as unit tests are added managing the state (nodes, print settings, Smart Slice state, etc.) will get tricky. Offloading that into classes/functions that are dedicated to cleaning up the state from a previous unit test and setting it back up will be very helpful.

2021-01-11 23:05 UTC, jake-kirkland-teton commented
Alright. I have the required changes in. I think this is ok for another look over.

2021-01-12 14:17 UTC, bradymadams requested changes
I think the new location of the update properties logic looks fine. Maybe the name of the function could use some massaging so it's a little more clear what it's doing. What's your concern with it?

2021-01-12 14:17 UTC, bradymadams commented on SmartSlicePlugin/tests/mock.py
> +import threemf
Unused?

2021-01-12 14:17 UTC, bradymadams commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +    def makeProblemMeshData(self, name_string):
If `self` isn't used in a class function then making it `static` is preferred.

We usually don't include type information in variable/argument names. Using a type annotation is preferred.

2021-01-12 14:17 UTC, bradymadams commented on SmartSlicePlugin/utils/__init__.py
> +def updateProperties(property_dict: dict, func: callable, property_object, property_object_type: str):
[callable is an actual Python built-in function](https://docs.python.org/3.5/library/functions.html#callable). Use the `Callable` type from the typing module and don't forget to include the argument types with it.

I like type annotations, so I like when I see them added to the code, but I think they're most helpful when the whole function is annotated and not just partially. So I'd add one for `property_object` as well.

And using `dict` is fine for a type annotation if any generic dictionary is acceptable, but if there's any required structure to it, using `Dict` from `typing` would be preferred. [See this for more info](https://stackoverflow.com/questions/37087457/difference-between-defining-typing-dict-and-dict).

2021-01-12 16:16 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/mock.py
> +import threemf
Ah yeah it is. Good catch.

2021-01-12 16:19 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +    def makeProblemMeshData(self, name_string):
Oh I see. I was not aware. That makes sense. I will get it switched over.

I will remember that. Do you require that I go in and change the code in proxy to fix this? I am only setting an existing variable.

2021-01-12 16:32 UTC, bradymadams commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +    def makeProblemMeshData(self, name_string):
Not sure I know where in the code you're referring to, or which of my comments you're referring to.

But generally, style updates to code that is not changed in the current PR are a judgment call. I think it's fine to hit a few spots for cleanup, but making dozens of changes can sometimes overwhelm an already complex PR.

If you're referring to the static method change request - in Python that is somewhere between a software design and style issue. I'd be more apt to change that if I came across it.

https://tetoncomposites.atlassian.net/wiki/spaces/DEV/pages/357040133/Coding+Style

2021-01-12 16:35 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +    def makeProblemMeshData(self, name_string):
Sorry that was unclear. I got the static method changed. That one is on me.

The one in question was the naming of `_sliceStatusEnum`, which is used in the Proxy class.

2021-01-12 16:41 UTC, jake-kirkland-teton commented on SmartSlicePlugin/utils/__init__.py
> +def updateProperties(property_dict: dict, func: callable, property_object, property_object_type: str):
Fair enough. I was not clear on the `callable/Callable` distinction. 

I thought about the `property_object` annotation, but it requires a couple of different types of objects depending on where the function is called from. How do I handle the that in that situation? In one case it is an `ExtruderStack`, in another case it is a `PerObjectContainerStack`. Do I just call it a generic `Stack`?

And alright. I will read that post and it sounds likely that it will be a `Dict` from `typing` instead. Thanks!

2021-01-12 16:44 UTC, bradymadams commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +    def makeProblemMeshData(self, name_string):
That looks like it touches way too much code for it to be a harmless style update.

Every code base is going to have imperfections that don't align with our adopted style or design philosophies. Usually it's from legacy code (created before an adopted style, etc) or was missed in a PR review. This is one of those cases. Sometimes it might be harmless to update it, other times it might be risky. Since this particular one affects QML and many other Python files, I think it's much too risky.

2021-01-12 16:47 UTC, jake-kirkland-teton commented on SmartSlicePlugin/tests/test_smartslice_mesh.py
> +    def makeProblemMeshData(self, name_string):
I agree with that assessment and that is what I was thinking. That is why I wanted to clarify if you were expecting I change it for the PR. I certainly would have done it if asked.

2021-01-12 16:59 UTC, bradymadams commented on SmartSlicePlugin/utils/__init__.py
> +def updateProperties(property_dict: dict, func: callable, property_object, property_object_type: str):
For `property_object` you should ask yourself what types will work and what won't work (will cause an exception). If anything that derives from `Stack` will work with the function then that's the proper type. If not, and it _must_ be one of the other specific two stack types then you should use [Union](https://docs.python.org/3/library/typing.html#typing.Union).

And now that we've clarified what the type likely is, this points out another place where naming could be improved. If the type is `Stack` then it would be a lot more clear if the argument was named `stack` or something similar. Names like property, object, key, etc. are ambiguous. Sometimes they're unavoidable when writing truly abstract code, but they should be avoided if at all possible.

Think about coming across your code as a developer and trying to figure out what it does. If you see:

```python
def foo1(stack: Stack):

def foo2(property_object):
```

`foo1` is _way_ more clear on how I use it.

2021-01-12 17:12 UTC, jake-kirkland-teton commented on SmartSlicePlugin/utils/__init__.py
> +def updateProperties(property_dict: dict, func: callable, property_object, property_object_type: str):
I see. Alright. That actually makes sense. I believe in this case the function will accept any `CuraContainerStack` so I will be labeling it as such. 

And that is a very good point. The names are ambiguous. I have changed them to be clearer, once I commit them let me know what you think of the new names. I agree, your example shows a very good point. Thank you for taking the time to help me learn.

2021-01-12 19:02 UTC, bradymadams reviewed
The types look good.

2021-01-12 19:02 UTC, bradymadams commented on SmartSlicePlugin/utils/__init__.py
> +            if container_stack_type == "settings_stack":
I know this logic was already there, but sometimes as code gets cleaned up other things become more apparent. Generally, it's not great design to use strings to control logic flow. Again, as a user of this function it's not immediately obvious to me what I should be sending for `container_stack_type` - I would have to read the code to understand what it's used for. Compare to something like:

```python
def updateContainerStackProperties(...., get_setting_definition: bool):
```

This would be a little more clear to me. However, I'm questioning why the call to `getSettingDefinition` even needs to be conditional. Couldn't it just be called every time regardless of the "stack type"?

2021-01-12 19:24 UTC, jake-kirkland-teton commented on SmartSlicePlugin/utils/__init__.py
> +def updateContainerStackProperties(property_dict: Dict[str, Any], func: Callable[[CuraContainerStack, str, Any, type, SettingDefinition], None], container_stack: CuraContainerStack, container_stack_t
Will do.

2021-01-12 19:26 UTC, jake-kirkland-teton commented on SmartSlicePlugin/utils/__init__.py
> +            if container_stack_type == "settings_stack":
Hmmm. Fair point. I think we absolutely could call it every time regardless. I think I was assuming it was specific to the `PerObjectContainerStack` but even then I think just checking to ensure it isn't `None` would be fine. I'll adjust that and test it.

2021-01-13 14:18 UTC, bradymadams approved these changes

2021-01-13 14:25 UTC, bradymadams commented
Will merge pending approval from @dougkenik

2021-01-13 15:39 UTC, dougkenik requested changes
Some user experience things I am noticing:

1. What happens if I open a result from a previous saved validation / optimization where the "problem meshes" were not returned? It looks like we are trying to display something still? My suggestion would be to not show the results buttons if we open a project without the appropriate data (e.g. from a previous release)
2. If I run a job with the new code, and then open a job from a previous release without problem meshes, the problem meshes returned from the first job are still present. This makes me think we are not clearing the data when we open a project?

2021-01-13 15:53 UTC, jake-kirkland-teton commented
1. I was thinking we could still show the popup with the extra instructions and information in that case, which is why the buttons are left there. I completely understand how that could be a bit of a confusing/poor UX so I will remove the buttons.
2. Hmmm. I had thought I was but that might not be the case. I will investigate.

2021-01-13 19:39 UTC, dougkenik requested changes
Run an optimization that fails to optimize, save it, and then open it. Cura crashes with the below message:


Traceback (most recent call last):
  File "X:\4.6-exe\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 1013, in event
  File "X:\4.6-exe\build\inst\lib\python3.5\site-packages\UM\Qt\QtApplication.py", line 464, in event
  File "X:\4.6-exe\build\inst\lib\python3.5\site-packages\UM\Event.py", line 218, in call
  File "X:\4.6-exe\build\inst\lib\python3.5\site-packages\UM\Signal.py", line 332, in __performEmit
  File "C:\Users\DougKenik\AppData\Roaming\cura\4.6\plugins\SmartSlicePlugin\stage\SmartSliceScene.py", line 516, in _process_mesh_analysis
    job.callback()
  File "C:\Users\DougKenik\AppData\Roaming\cura\4.6\plugins\SmartSlicePlugin\SmartSliceExtension.py", line 270, in afterSmartSliceNodeInit
    self.cloud.processAnalysisResult(selected_row)
  File "C:\Users\DougKenik\AppData\Roaming\cura\4.6\plugins\SmartSlicePlugin\SmartSliceCloudConnector.py", line 1005, in processAnalysisResult
    resultData = ResultTableData.analysisToResultDict(0, job.getResult().analyses[0])
  File "C:\Users\DougKenik\AppData\Roaming\cura\4.6\plugins\SmartSlicePlugin\3rd-party\cpython-common\pywim\__init__.py", line 99, in __getitem__
    return super().__getitem__(key)
IndexError: list index out of range

2021-01-13 20:17 UTC, jake-kirkland-teton commented
Yeah I discovered this one a bit ago. It happens without the problem meshes too. I started a ticket. 
https://app.zenhub.com/workspaces/smartslice-5ef3719d317b88001a6dc21e/issues/tetonsim/is-cura-ui/368

2021-01-13 22:06 UTC, dougkenik approved these changes
Ok. The UI looks good now.

2021-01-13 22:08 UTC, merged