initial zero in skin_angles list crash bugfix
tetonsim/is-cura-ui pull request #373
Opened 2021-01-15 22:27 UTC by AijunHall

`skin_angles = SettingFunction(skin_angles)(self._propertyHandler)` is the problem line from `UM/UM/Settings/SettingFunction.py`

If the given `str` from `self._propertyHandler.getExtruderProperty("skin_angles")` doesn't include the correctly formatted brackets `[]`, or if an element in the 'to-be-list' has a preceeding 0 as shown in the ticket gif, then 
`SettingFunction(skin_angles)(self._propertyHandler)` will return `NoneType` instead of a `list`.

With verifying the `list` type beforehand here, Cura won't crash. And 'invalid' inputs to the skin angles will be brought up by `UM/UM/Settings/SettingFunction.py` 

Here is the error brought up in the debugger, (no crash):
```
ERROR - [MainThread] UM.Settings.SettingFunction.__init__ [67]: Parse error in function (INPUTTED_SKIN_ANGLES) for setting: invalid token (eval, line 1)
```

2021-01-15 22:42 UTC, AijunHall commented
One thing to consider, this doesn't account for when a user would enter an integer into the skin_angles. It would go to the default `else: print_config.skin_orientations.extend((45, 135))`

I can change that, but I just went off the setting description: 'A list of integer line directions'

![image](https://user-images.githubusercontent.com/54338983/104785558-a18f2080-573f-11eb-88cd-8ec6180e56e4.png)

2021-01-15 23:15 UTC, jake-kirkland-teton commented
I believe it might be a better strategy to have our code reset the showing value to a valid one in the event of an invalid input, rather than just sending the default values back to us. That way, the user doesn't think they have entered a value that is not actually representative of what we are using to calculate. Thoughts @bradymadams?

2021-01-16 14:36 UTC, bradymadams requested changes
This is a tough one, as @jake-kirkland-teton has alluded to. I don't think we want to set the skin orientations to a value that the user might not be expecting, and I don't think we can reset the property because we could be resetting it while the user is editing it which would be annoying UX.

When the skin_angles property can't be parsed and comes back as None I would consider keeping the current logic you have, but also add a message to the returned `errors`. This means one of two things would happen:

1. If the user is in the middle of editing the skin_angles, and ultimately change it to something valid the error will eventually go away.
2. If the user has edited skin_angles to something invalid we will be setting an error indicating such and they'll be notified that they need to fix it before they can proceed.

2021-01-16 14:36 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +        if type(skin_angles) is list and len(skin_angles) > 0:
I realize the code above is doing the same thing, but it must be pretty old, because we prefer using [isinstance](https://docs.python.org/3/library/functions.html#isinstance) now.

However, I think `if skin_angles:` would be False in both the case that skin_angles is None and when it's a list with 0 length.

2021-01-18 18:07 UTC, AijunHall commented
> I would consider keeping the current logic you have, but also add a message to the returned errors.

I just borrowed the same error handling code that I saw throughout this script for this skin_angles field @bradymadams .  I still do the `list` type check, since in the event that the user enters an `int` value, it raises a fatal error when it attempts to add it to the `skin_orientations` for not being iterable.

> That way, the user doesn't think they have entered a value that is not actually representative of what we are using to calculate.

Now with this setup error, the user should only be using their own valid inputs since they'll be made aware when invalid inputs are raised @jake-kirkland-teton

2021-01-19 00:29 UTC, jake-kirkland-teton requested changes
This change is good, I like the use of disabling the validate button and returning the feedback to the user that way. Just a last couple changes and I think this will be good to go:

1. While I was testing this, I changed the other "list" property and got the same crash (`"Infill Line Directions"`). We should catch this crash as well. I think that is the only other `list` property, but we should double check.

2. In the error message we should have an example of a `list` for non-programmers so it is clearer what we are expecting the user to put in. Something helping specify the brackets, like "(e.g. [90])" should work, but I think someone who is not clear what a `list` is might struggle to fix the problem.

2021-01-19 15:15 UTC, bradymadams requested changes
@jake-kirkland-teton good catch. @AijunHall let's make the same fix for the infill line directions in this PR.

As for the message let's just go with: "Enter a valid list of angles". The line directions are only shown in the Expert settings, so anyone mucking around in those should be able to figure it out, or at least reset the property and start over.

2021-01-19 15:18 UTC, bradymadams commented
@AijunHall I also forgot to tell you about version incrementing. In each PR you'll want to increment the revision number of the version. Our versions are `MAJOR.MINOR.REVISION`, so you want to increment the third number. In this repo you'll find the version number in two files (both need updated):

```
packaging/package.json
SmartSlicePlugin/plugin.json
```

The current version is 20.2.12 so you'll change it to 20.2.13 in this PR.

2021-01-19 20:29 UTC, bradymadams requested changes
Please include the property name in the error message like you had before: `"Invalid <i>Top/Bottom Line Directions</i>: {}".format(skin_angles)`

It's important the user know which property is creating the error.

2021-01-19 20:29 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceJobHandler.py
> -            print_config.infill.orientation = infill_angles[0]
This shouldn't be removed, it is an important check separate from the invalid list issue.

2021-01-19 20:46 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceJobHandler.py
> -            print_config.infill.orientation = infill_angles[0]
Did I remove these lines? I thought I just moved 190-193 to be within the new `list` type check, where its now lines 197-200.

Because the crash is caused by the `len()` statements, so shouldn't these lines be within the `list` check?

2021-01-19 20:48 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceJobHandler.py
> -            print_config.infill.orientation = infill_angles[0]
You're right, not sure how I missed that. Sorry about that.

2021-01-19 21:24 UTC, AijunHall commented
for `infill_angles` I changed the error message slightly since this field only has 1 list value. The existing error message that tells the user to only input 1 list value for the `infill_angles` comes up as well.

![image](https://user-images.githubusercontent.com/54338983/105094660-75361580-5a59-11eb-9088-17106ce2f951.png)

2021-01-19 22:34 UTC, bradymadams approved these changes
Looks good to me. Will merge pending Jake's approval.

2021-01-19 22:57 UTC, jake-kirkland-teton reviewed
I like it. Looks good to me! Nice work.

2021-01-19 22:57 UTC, jake-kirkland-teton approved these changes

2021-01-19 23:00 UTC, merged