no optimize results load crash bugfix
tetonsim/is-cura-ui pull request #379
Opened 2021-01-21 20:13 UTC by AijunHall

This fix is simple, and prevents a crash while also saving the user's anchors, loads, and settings, but it might not be targeting the root of the problem.

The crash is caused because in this scenario, where a user opens a project they saved at the point of being told there are no optimized results, `job.getResult().analyses` returns an empty list and can't be indexed.

The reason I say it might not be targeting the root of the problem, this might have something to do with the activity of `SmartSliceCloudConnector.status` . Maybe this is why the analyses is lost because of a 'bad' activity status update?

This "no optimize results load scenario" is the only point at which I see this type of status change.
![image](https://user-images.githubusercontent.com/54338983/105406299-16030d00-5be1-11eb-9078-0a13e62d5f7e.png)

Not too sure since I'm still prowling over the code base, but I want to bring it to attention.

2021-01-22 14:18 UTC, bradymadams reviewed
Would the `job.job_type` ever be `optimization` in a similar scenario? If so, I think a similar check would be needed on line 1011, or in the `setResults` function.

I also wonder if we need to change the save functionality so that incomplete results are never saved anyway, thus making it so this conditional evaluates to False:

https://github.com/tetonsim/is-cura-ui/blob/27461705a03a6cbe9256ed02b73132fa6f85237d/SmartSlicePlugin/SmartSliceExtension.py#L267-L270

2021-01-22 17:47 UTC, jake-kirkland-teton commented
@bradymadams I am doing a couple tests to try to get that situation, but I think if the results are saved with the table the `.analyses` will always be present, though it may make sense to add the check there, because, as you previously stated, shit happens.

On the subject of rewriting the saving system, I think that is up to @dougkenik  to make that call. If we want to properly save the results of a "Cannot Optimize" scenario so we can load them again, there will need to be some changes made to ensure the data is saved, perhaps a new status added. If not, I think your adjustment would work well.

2021-01-22 20:31 UTC, dougkenik commented
I don't think we should save the results of a failed job. We should revert back to the setup of that job and save it

2021-01-22 20:38 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +            return
Would this be a better catch to include the optimization `job.job_type`?

2021-01-22 21:09 UTC, AijunHall commented
> Would the job.job_type ever be optimization in a similar scenario?

@bradymadams In my limited messing around, unless optimization succeeds with
`SmartSliceCloudStatus.BusyOptimizing -> SmartSliceCloudStatus.Optimized`

the `job.job_type` won't be `optimization`

When the optimization fails the status gets kicked back
`SmartSliceCloudStatus.BusyOptimizing -> SmartSliceCloudStatus.ReadyToVerify`

and there isn't a job type update.  Let's see what comes of @jake-kirkland-teton 's testing

> I also wonder if we need to change the save functionality so that incomplete results are never saved anyway, thus making it so this conditional evaluates to False:

I'm also glad you brought this up, because this is the problem area for #375 where `results` is an unexpected `None` when saving a project before having a complete `JobType.validation`

_This line comes before your snippet with the `if results` and causes the crash in 375_

https://github.com/tetonsim/is-cura-ui/blob/1a503283749ca6d1105d972503c6c22d737000bc/SmartSlicePlugin/SmartSliceExtension.py#L258

So the relation between these two issues is probably the save functionality because of these `result` attributes being lost when the user does a weird combination of inputs then saves.

2021-01-22 21:28 UTC, jake-kirkland-teton commented
So Aijun is correct, I was unable to get a job_type to be `optimized` and not have `.analyses`. That doesn't mean it can't happen, but I tried a few different weird things and never caused a crash.

On the subject of saving incomplete results, since Doug mentioned we should only save the Boundary Conditions and not the results of we fail to optimize, I feel we should go with Brady's suggestion. 
@AijunHall  Do you think you could write a reasonable check to ensure the results are present or prevent saving them to resolve both issues?

2021-01-22 21:39 UTC, AijunHall commented
> Do you think you could write a reasonable check to ensure the results are present or prevent saving them to resolve both issues?

@jake-kirkland-teton Sure thing.

2021-01-25 17:13 UTC, bradymadams reviewed
I'm not sure I understand the change in SmartSliceExtension.py. Can you explain it? It seems like if the conditional on line 256 is False then line 270 is going to be problematic (will `cloudJob` be None?).

2021-01-25 20:35 UTC, AijunHall commented
@bradymadams I see the problem now.

The previous commit does fix the 375 crash, but `cloudJob` does come out as None in the "no validation load" scenario

The crash is caused by a `results.fea_results` check when `result` is None, so I thought nesting the lines within the
256 conditional would be a reasonable fix. 

I'll simplify it. I'm also looking into the save functionality, which might be a better approach.

2021-01-25 23:26 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceExtension.py
> +            elif job.type == pywim.smartslice.job.JobType.validation and (not cloudJob or not cloudJob.getResult()):
Why is it limited to `validation` here?

2021-01-25 23:36 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceExtension.py
> +            elif job.type == pywim.smartslice.job.JobType.validation and (not cloudJob or not cloudJob.getResult()):
No idea to be honest. I assumed `optimization` would be caught in the first conditional. I'll add it in.

2021-01-26 21:51 UTC, AijunHall commented
> I think if we use the ReadyToValidate to prevent the results from saving in that case, it should work.

Would using the status of the result be better than using the cloud status @jake-kirkland-teton ? For the optimize issue, this is the scenario where the `no_solution_found` status would be brought up specifically, vs the broad application of `ReadyToValidate`
(to prevent problematic results from downloading)

https://github.com/tetonsim/pywim/blob/be6eddab85d08c414f1f544b0584a87fcdc9bc80/pywim/smartslice/result.py#L8-L11

2021-01-26 21:54 UTC, bradymadams commented
This looks good to me, but I just requested Doug's review on this. He understands the saving logic better than I do.

2021-01-26 21:57 UTC, jake-kirkland-teton commented
> 
> 
> > I think if we use the ReadyToValidate to prevent the results from saving in that case, it should work.
> 
> Would using the status of the result be better than using the cloud status @jake-kirkland-teton ? For the optimize issue, this is the scenario where the `no_solution_found` status would be brought up specifically, vs the broad application of `ReadyToValidate`
> (to prevent problematic results from downloading)
> 
> https://github.com/tetonsim/pywim/blob/be6eddab85d08c414f1f544b0584a87fcdc9bc80/pywim/smartslice/result.py#L8-L11

I think that would work well actually. I would double check to ensure that status is always present when you need to check for it, but as long as it is, I think that is a great idea.

2021-01-26 22:05 UTC, AijunHall commented
Good point to bring up, especially considering all these bugs I'm encountering are None type errors.

The smartslice result object gets initialized with the status as I see here, so unless `.getResult()` has some weird behavior I'm not aware of I think this is solid.
https://github.com/tetonsim/pywim/blob/be6eddab85d08c414f1f544b0584a87fcdc9bc80/pywim/smartslice/result.py#L39-L45

2021-01-26 22:35 UTC, dougkenik requested changes

2021-01-26 22:35 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceExtension.py
> +        if cloudJob and not cloudJob.getResult().status is pywim.smartslice.result.ResultStatus.no_solution_found:
Is it possible for `cloudJob.getResult()` to be `None` here?

2021-01-26 22:35 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceExtension.py
>              self._storage.setEntryToStore(
I'm a little fuzzy here.... If this is a validation, and not an optimization, what is it storing for `self.proxy.resultsTable.getSelectedResultId()` ? There is technically nothing selected, because there is only 1 result

2021-01-26 22:42 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceExtension.py
> +        if cloudJob and not cloudJob.getResult().status is pywim.smartslice.result.ResultStatus.no_solution_found:
Not sure 100%, but since that was a previous check, I will include it back in.

2021-01-26 22:53 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceExtension.py
>              self._storage.setEntryToStore(
This is previously existing code I just shifted so I can't be much of an authority here.

I'm doing some testing, so far and it seems to be storing 0. It does this for validations AND optimizations actually.
`self.proxy.resultsTable.getSelectedResultId():  0`

Is this deprecated?

2021-01-26 22:55 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceExtension.py
>              self._storage.setEntryToStore(
No - select a different row in the optimization table and save that. The value should change to that row

2021-01-26 23:04 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceExtension.py
>              self._storage.setEntryToStore(
Heres the reference in the repo I found if this helps either of us:

https://github.com/tetonsim/is-cura-ui/blob/2b2b71cc8dcb3a42fd7527358459acc0b9eac8e1/SmartSlicePlugin/SmartSliceCloudProxy.py#L789-L791

2021-01-27 00:38 UTC, dougkenik approved these changes
Looks good. We will need to test it thoroughly

2021-01-27 12:56 UTC, bradymadams approved these changes

2021-01-27 12:56 UTC, bradymadams commented
Will merge pending approval from @jake-kirkland-teton

2021-01-27 17:36 UTC, jake-kirkland-teton approved these changes

2021-01-27 17:57 UTC, merged