R20.2 bug 374
tetonsim/is-cura-ui pull request #383
Opened 2021-01-27 13:23 UTC by dougkenik

Fixes #374

2021-01-27 16:54 UTC, jake-kirkland-teton requested changes
There is still one situation that causes this bug. If you change a print setting while the validate button is "sick" and you make it acceptable, the validate button becomes active but the resolved window remains.
![Bug374](https://user-images.githubusercontent.com/62028020/106025047-a16b1b00-6085-11eb-9ce0-7c317816be96.gif)

2021-01-27 21:23 UTC, dougkenik commented
Good to go now

2021-01-27 21:31 UTC, AijunHall approved these changes
Been trying to reproduce the error overlapping for a while now, and haven't been able to do it. Looks like you've got it fixed 100% on the user end.

2021-01-28 14:00 UTC, bradymadams approved these changes

2021-01-28 14:00 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceMain.qml
> +                                return
This return can be removed, but probably not worth the effort unless you need to make some other changes.

2021-01-29 02:08 UTC, jake-kirkland-teton approved these changes

2021-01-29 13:30 UTC, merged