unit test fix
tetonsim/is-cura-ui pull request #463
Opened 2021-02-22 17:20 UTC by colman-hartinger

Still testing to make sure that action will fail when unit test fails

2021-02-22 22:29 UTC, bradymadams requested changes
In build_unit_tests.sh there is:

`git clone -b ${1} --depth 1 https://github.com/Ultimaker/dm_materials materials`

That repo doesn't exist. Should it be fixed? Or is it even necessary since the tests seem to pass without the intended fdm_materials repo?

2021-02-22 22:29 UTC, bradymadams commented on build_unit_tests.sh
> +mv pywim/pywim /srv/cura/Cura/plugins/SmartSlicePlugin/3rd-party/cpython-common
Why is this needed when it wasn't before?

2021-02-22 22:44 UTC, colman-hartinger commented on build_unit_tests.sh
> +mv pywim/pywim /srv/cura/Cura/plugins/SmartSlicePlugin/3rd-party/cpython-common
we were just using a pip install for pywim before but that seemed to be an old version, If you loo'k at [this](https://github.com/tetonsim/is-cura-ui/runs/1956109651?check_suite_focus=true) action that failed it was because pywim didn't have the 'ModelRegion' attribute and this fixed that

2021-02-22 22:46 UTC, bradymadams commented on build_unit_tests.sh
> +mv pywim/pywim /srv/cura/Cura/plugins/SmartSlicePlugin/3rd-party/cpython-common
I actually just published the new pywim about an hour ago, so `pip` should work now. I'm fine with it cloning from github as well, but it should probably checkout a specific branch. `master` will usually lag.

2021-02-22 22:52 UTC, colman-hartinger commented on build_unit_tests.sh
> +mv pywim/pywim /srv/cura/Cura/plugins/SmartSlicePlugin/3rd-party/cpython-common
I think it's smoother just to do a pip install so I removed those lines. Should I note in the README that if tests are failing to change to the latest branch of pywim?

2021-02-22 22:56 UTC, bradymadams commented on build_unit_tests.sh
> +mv pywim/pywim /srv/cura/Cura/plugins/SmartSlicePlugin/3rd-party/cpython-common
Let's leave it out for now. I'd like to think about that and how we might be able to more reliably target the right branches of the external dependencies.

2021-02-22 23:10 UTC, bradymadams commented
@colman-hartinger did you see my other question about the fdm_materials repo?

2021-02-22 23:15 UTC, colman-hartinger commented
> @colman-hartinger did you see my other question about the fdm_materials repo?

Totally missed that, just fixed the typo. Although not necessary right now It still seems like a good idea to have that in case we want to test material changes

2021-02-23 00:38 UTC, bradymadams approved these changes

2021-02-23 00:38 UTC, merged