R21.0 welcome screen
tetonsim/is-cura-ui pull request #477
Opened 2021-03-07 13:44 UTC by dougkenik

I still need to get the complete URL for the welcome video, but a draft review would be great here:

- Created a welcome screen on login
- Added videos for welcome and tutorials on a second screen after welcome
- Video screen is accessible via Extensions or the left toolbar (?)
- The videos are GIFS I created and hosted on our website, so we can easily update them
- Clicking on a video takes the user to the Help webpage instead of displaying the video - displaying the video in-product was going to be too much work
- I decided not to have a "Don't show me this again" checkbox on the Welcome screen in case we add more functionality and want to re-purpose. It's very easy to dismiss it right now
- I added a Preferences class which can be used around our SmartSlice application. We had preferences strewn about, so I wanted to consolidate

We could add the videos in-product if we created them as GIF's. I am unsure how useful this would be, but I am open to the discussion.

2021-03-08 14:20 UTC, bradymadams requested changes
This is just a brief review of the functionality and a couple other comments. I'll let @colman-hartinger review the code first.

1. Unit tests are failing.
2. I don't see any gifs, and I see these errors:

```
QML AnimatedImage: Error Reading Animated Image File https://www.tetonsim.com/hubfs/tutorial1.gif
```

![image](https://user-images.githubusercontent.com/23110600/110333187-870a5280-7fde-11eb-8091-bcae6b3c6544.png)

2021-03-08 14:20 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceWelcome.qml
> +                        source: 'https://www.tetonsim.com/hubfs/tutorial2.gif'
1. How stable do we think these links are? Is there a risk that someone might change this without knowing the plugin is referencing it?
2. Do we have a consolidated place in the plug-in code (outside of QML) where we are specifying links. If they're scattered, it might be a good idea to consolidate so when we need to change something we can easily find all the links and change the necessary ones without risk of missing any.

2021-03-08 17:12 UTC, colman-hartinger commented
It looks like the unit tests are failing because of one of the mocked objects not being initialized right. I'll look into that but I'm not sure that it was a problem introduced by this PR. I haven't gone through the code yet but when you aren't in full screen the new welcome screen gets a little funky. I think that it should look good for all allowable screen sizes in cura

![welcome](https://user-images.githubusercontent.com/62404177/110355757-ce9cd880-7ff6-11eb-999f-f5ee7e72ff81.png)

2021-03-08 17:50 UTC, colman-hartinger requested changes

2021-03-08 17:50 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +        self._preferences = connector.extension.preferences
This is the line that is causing the unit tests to fail. I don't see anything wrong with calling the preferences from the cloud connector so I'll add a fix so that object is properly mocked

2021-03-08 17:50 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +        self._first_name = "Friend"
Is the welcome screen supposed to display the users name? After I login it still says "Welcom to Smart Slice, Friend"

2021-03-08 17:50 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +        if self.app_preferences.getPreference(Preferences.SaveDebug):
@bradymadams should we get rid of the debug package? It seems obsolete now that we can just save 3mfs with smartslice data

2021-03-08 17:50 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +    def setIntroScreenVisible(self, intro_screen_visibile: bool):
I think this should be renamed to `setIntoScreenVisibility` since this is also used to turn off the visibility

2021-03-08 17:50 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +    def setWelcomeScreenVisible(self, welcome_screen_visibile: bool):
same issue as above comment

2021-03-08 17:55 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +        if self.app_preferences.getPreference(Preferences.SaveDebug):
The "debug" package is a slightly different format than what is saved by Cura. The reason is because we developed our 3MF format for the back-end before Cura implemented the plugin metadata save logic and they picked a different format. Eventually, I'd like to have the back-end recognize both formats (or move to all JSON). But for now I think there's a benefit to leaving it in. It allows Jeff and others to quickly save a 3MF that they can submit to the smartslice engine locally for dev and testing.

2021-03-09 01:36 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceCloudConnector.py
> +        self._first_name = "Friend"
Is should display user name. "Firend" is a default. I'll check on this, but it should be displaying your name

2021-03-09 01:38 UTC, dougkenik commented on SmartSlicePlugin/stage/ui/SmartSliceWelcome.qml
> +                        source: 'https://www.tetonsim.com/hubfs/tutorial2.gif'
1. They are on a landing page, which we can change at any time. They can change at any time, which was the reason for putting them on the landing page. For example, when this functionality is released, the welcome video needs to change with he UI. If there is a better approach, I am open to it - I thought this was best so we can update the help videos and these GIFS all in Hubspot
2. No - good idea, and I will look into that. Should this be a different ticket though?

2021-03-09 14:07 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceWelcome.qml
> +                        source: 'https://www.tetonsim.com/hubfs/tutorial2.gif'
1. I wasn't suggesting they not be editable or that they be put in the repo. I agree with hosting them so we can update them. What I don't have a feel for is how hubspot hosts them and who has access to them. Is it possible for someone to come across the gif, think they're cleaning something up, and unintentionally rename or move it? If you think that's unlikely, it's fine - it's just something I always think about when I see a URL hardcoded client side.
2. If there's not a central place for URLs yet, then yes, separate ticket.

2021-03-09 14:08 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceWelcome.qml
> +                        source: 'https://www.tetonsim.com/hubfs/tutorial2.gif'
And the more serious problem would be if we ever moved away from hubspot - all those links would get broken.

2021-03-09 14:40 UTC, dougkenik commented on SmartSlicePlugin/stage/ui/SmartSliceWelcome.qml
> +                        source: 'https://www.tetonsim.com/hubfs/tutorial2.gif'
> 1. I wasn't suggesting they not be editable or that they be put in the repo. I agree with hosting them so we can update them. What I don't have a feel for is how hubspot hosts them and who has access to them. Is it possible for someone to come across the gif, think they're cleaning something up, and unintentionally break the link by renaming or moving it? If you think that's unlikely, it's fine - it's just something I always think about when I see a URL hardcoded client side.
> 2. If there's not a central place for URLs yet, then yes, separate ticket.

If we want to host them somewhere else besides in hubspot, then we would need to agree as to where. If you have an idea of how to do it, or how you would prefer it done - then please let me know.

2021-03-09 16:01 UTC, dougkenik commented on SmartSlicePlugin/stage/ui/SmartSliceWelcome.qml
> +                        source: 'https://www.tetonsim.com/hubfs/tutorial2.gif'
There is definitely a chance that the videos could get deleted or replaced on the landing page - or the landing page could get deleted entirely. The only real steps we can take to protect it is to name it in such a way that it won't get deleted.

2021-03-09 16:35 UTC, bradymadams commented on SmartSlicePlugin/stage/ui/SmartSliceWelcome.qml
> +                        source: 'https://www.tetonsim.com/hubfs/tutorial2.gif'
Okay :+1:

2021-03-09 17:33 UTC, dougkenik commented
@colman-hartinger - screen size is dynamic now

2021-03-10 18:29 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceCloudProxy.py
> +    welcomeScreenVisibleChanged = pyqtSignal()
Intro screen contains the welcome message. Welcome screen contains the videos. You can navigate to the welcome screen directly through product (don't want to show the intro screen if someone tries to access the welcome screen in product)

2021-03-10 18:30 UTC, dougkenik commented on SmartSlicePlugin/components/SmartSliceTooltip.qml
> +            // renderType: Text.NativeRendering
The tooltip text was displaying very poorly in the video tooltips. It is because of Native Rendering. This has happened before when we implemented the login screen

2021-03-10 18:33 UTC, dougkenik commented
> Everything looks a lot better now when not in full screen although the screen with the videos still has some overlapping text. Have you thought about doing this as a popup? I think a popup would be less intrusive and allow the user to switch between messing around with the part in smart slice and choosing which tutorial to watch

Can you share a sreenshot of what the overlaping text looks like? We agreed on the current design as-is. We could allow the user to drag and resize the welcome screen, as well as access the scene behind it if necessary, but when you click on a vide, it opens the web browser, which allows you to dismiss the welcome screen and follow along. Is that not good enough? What features of a popup are better?

2021-03-10 19:08 UTC, colman-hartinger commented
![Screenshot 2021-03-10 11:51:21](https://user-images.githubusercontent.com/62404177/110681751-646f6980-8197-11eb-9551-9a19b374cd1e.png)

heres the welcome screen when I'm not in using cura in fullscreen.

>What features of a popup are better?

The only benefits I could see for a popup over what is currently in place is that it would allow the user to go through a couple different workflow tutorials without having to open and close the welcome screen. I also personally believe that non "mission critical" aspects of a program should be as in-obtrusive as possible. That being said I don't think there's that big of a difference between 2 or 3 clicks to remove the intro/welcome screen vs 1 click to hide a popup

2021-03-12 17:43 UTC, dougkenik commented
The welcome video is now in help, so this can turn into a full-fledged review

2021-03-12 18:32 UTC, colman-hartinger approved these changes
Everything looks good to me. Also I'll add the fix for the failing tests in r21.0-tests since it will be a cleaner  solution to pass the the correct objects in using CuraStateManagement.

2021-03-15 15:33 UTC, bradymadams reviewed
One trivial thing I noticed. Some of the JS in the QML is missing semi-colons.

2021-03-15 15:33 UTC, bradymadams commented on SmartSlicePlugin/SmartSlicePreferences.py
> +        t = self._preference_base + preference
Unnecessary line?

2021-03-19 16:13 UTC, bradymadams approved these changes

2021-03-19 16:13 UTC, merged