R21.0 unit test filesystem
tetonsim/is-cura-ui pull request #484
Opened 2021-03-11 02:29 UTC by AijunHall

Tried to consolidate the model path retrieval, and the plugin metadata retrieval into `getModelData()`

I also moved the json unpacking functionality to the File System as well.

I wanted to get as much of the path strings out of the State Management System as possible, so I thought it might be more appropriate to initialize the File System with a default model to use in unit testing, instead of Cura.

The README also now defines how files should be named and structured to be properly loaded. Let me know your thoughts on this.

2021-03-11 02:42 UTC, AijunHall commented
@colman-hartinger The two initial default files in the model storage repo are just the same ones from the zip you showed here:

https://github.com/tetonsim/is-cura-ui/pull/483#issuecomment-796283348

2021-03-11 20:15 UTC, bradymadams requested changes
1. You're doing a good job of type annotating the returns. Add type annotations to arguments as well.
2. I think it would be more extendible to store models in a directory and refer to a model by it's directory name, rather than by the STL.

For example:

```
root/
  model_A/
     ... some files ..
  model_B/
     ... some files
```

And then request to load a model by the name in the directory.

That will allow you to use specific file names within a directory and you don't have to iterate directories and assume what the file holds based off extension (which could be bug prone for JSON formats).

2021-03-11 20:15 UTC, bradymadams commented on SmartSlicePlugin/tests/CuraStateManagement.py
> +            stl_path, smartSliceData = self.filesystem.default_model
Use consistent naming styles. For local variables we use underscore separated lower case.

2021-03-11 20:15 UTC, bradymadams commented on SmartSlicePlugin/tests/FileSystem.py
> +class FileSystem:
I think `FileSystem` isn't a great name for this class. Something like `ModelLoader`, `ModelRetriever`, etc. might be a better representation of what it's actually doing.

2021-03-11 20:15 UTC, bradymadams commented on SmartSlicePlugin/tests/FileSystem.py
> +    def __init__(self, root_dir='SmartSlicePlugin/tests/models'):
Hardcoding path separators usually isn't good practice. I'd see if you can avoid that. I'd probably set `root_dir` to default to `None` (`Optional[str]`), and check for None in the body of the constructor - if it's None then build the path relative to `os.getcwd()`.

2021-03-11 20:15 UTC, bradymadams commented on SmartSlicePlugin/tests/FileSystem.py
> +            threeMFData = json.load(data)
This name is misleading. The data isn't in 3MF format.

2021-03-11 23:08 UTC, AijunHall commented
> I think it would be more extendible to store models in a directory and refer to a model by it's directory name, rather than by the STL.

Will do. How about something like this in regards to having specific consistent filenames to refer to.

```
root/
  model_A/
     model.stl
     plugin_metadata.json
  model_B/
     model.stl
     plugin_metadata.json
```

I originally thought something like this would be too cumbersome to setup in the first place, so if we go down this path, maybe we could come up with a way to properly setup the models and/or SmartSlice data to the models dir

2021-03-11 23:14 UTC, bradymadams commented
> I originally thought this would be too cumbersome to setup in the first place, so if we go down this path, maybe we could come up with a way to properly setup models and/or SmartSlice data to this dir structure

Your setup looks good to me. Can you elaborate on where you think the complications are?

2021-03-11 23:21 UTC, AijunHall commented
> Can you elaborate on where you think the complications are?

I don't think there are complications, I was just wondering about how to avoid setting these up manually - depending on how often we would need to add/change models

2021-03-12 17:37 UTC, bradymadams approved these changes
Looks good to me. I'll merge upon approval from @colman-hartinger

2021-03-12 18:06 UTC, colman-hartinger requested changes
Everything is looking pretty good and runs as expected. There do seem to be some mislabeled return types in ModelLoader.py once that is fixed I think this should be good to go

2021-03-12 18:06 UTC, colman-hartinger commented on SmartSlicePlugin/tests/ModelLoader.py
> +    def getSmartSliceData(self, metadata_path: str) -> Tuple[int, Dict]:
I would have this return `Tuple[any, any, any, any] since status, job_dict ... can also be None

2021-03-12 18:06 UTC, colman-hartinger commented on SmartSlicePlugin/tests/ModelLoader.py
> +    def getModelData(self, model_dir_path: str) -> Tuple[str, Tuple[int, Dict]]:
I would have the return type here be Tuple[any, any] and then add type annotations for smartslice_data and full_stl_path within the function

2021-03-12 18:50 UTC, bradymadams commented on SmartSlicePlugin/tests/ModelLoader.py
> +    def getModelData(self, model_dir_path: str) -> Tuple[str, Tuple[int, Dict]]:
If the type can be None I think using `Optional[T]` is better than `Any`.

2021-03-12 18:50 UTC, bradymadams commented on SmartSlicePlugin/tests/ModelLoader.py
> +    def getModelData(self, model_dir_path: str) -> Tuple[str, Tuple[int, Dict]]:
If the type can be None using `Optional[T]` is the standard annotation.

2021-03-12 19:02 UTC, bradymadams requested changes

2021-03-12 19:02 UTC, bradymadams commented on SmartSlicePlugin/tests/ModelLoader.py
> +    def getSmartSliceData(self, metadata_path: str) -> Tuple[any, any, any, any]:
This will probably result in an error. `any` isn't a standard Python keyword and it's not imported from anywhere. What you're probably trying to use is `Any` from the `typing` module. However, use `Optional` instead if you know what the type is.

2021-03-12 19:02 UTC, bradymadams commented on SmartSlicePlugin/tests/ModelLoader.py
> +    def getModelData(self, model_dir_path: str) -> Optional[T]:
When I wrote `Optional[T]` in a previous comment I wrote `T` to represent the type that the return is, if it's not None. `T` is commonly used as a generic placeholder. So if the return could be a string or None then the return type is `Optional[str]`.

It's important to use the proper types because good IDEs will pick it up and give you appropriate error checking and auto-completion.

2021-03-12 19:03 UTC, bradymadams commented on SmartSlicePlugin/tests/ModelLoader.py
> +    def getModelData(self, model_dir_path: str) -> Optional[T]:
And make sure you set the return type back to a `Tuple`

2021-03-12 19:04 UTC, bradymadams commented on SmartSlicePlugin/tests/ModelLoader.py
> +            smartslice_data: Tuple[any, any, any, any] = self.getSmartSliceData(full_metadata_path)
There's no need for the local annotation here since `getSmartSliceData` is annotated with the return type.

2021-03-12 19:05 UTC, AijunHall commented on SmartSlicePlugin/tests/ModelLoader.py
> +    def getModelData(self, model_dir_path: str) -> Optional[T]:
Colman just linked me to a VSCode extension that does the type def checking, so I'll get that setup.

2021-03-12 20:21 UTC, AijunHall commented
I realized the selectedRow is also an int, so I reflected that in the new PluginDataType

2021-03-12 20:23 UTC, colman-hartinger approved these changes
Everything looks good to me

2021-03-12 20:59 UTC, bradymadams approved these changes
Looks good. I didn't notice this earlier, but note that one of the style exceptions in the Cura plug-in is we use double quote strings instead of single quote. I'll merge this anyway and we can update it in a later PR when someone comes across it.

2021-03-12 20:59 UTC, merged