R21.0 custom surface
tetonsim/is-cura-ui pull request #493
Opened 2021-03-29 19:46 UTC by dougkenik

Functionality for custom surface selection and custom load selection. Need to use pywim r21.0-custom_surface

2021-03-29 20:38 UTC, colman-hartinger commented
Code review to Come, but my initial thought playing around with the new feature is that the load magnitude helper should be disabled in custom mode, I think it's safe to assume that an advanced user would have some intuition about converting N to Lbs 
![loadHelper 2021-03-29 14:35:17](https://user-images.githubusercontent.com/62404177/112897073-680e5600-909c-11eb-9561-ce3aeca27ed7.png)

2021-03-29 20:45 UTC, dougkenik commented
> Code review to Come, but my initial thought playing around with the new feature is that the load magnitude helper should be disabled in custom mode, I think it's safe to assume that an advanced user would have some intuition about converting N to Lbs
> ![loadHelper 2021-03-29 14:35:17](https://user-images.githubusercontent.com/62404177/112897073-680e5600-909c-11eb-9561-ce3aeca27ed7.png)
> 
> Edit:
> Also there are some merge conflicts in SmartSliceScene.py that need to be resolved

I turned off showing the images, but the slider is still there. Do you think the slider should disappear too?

2021-03-29 20:49 UTC, colman-hartinger commented
> I turned off showing the images, but the slider is still there. Do you think the slider should disappear too?

I don't think it will be used that much in custom mode since it only allows the selection of 4 values but I also don't think that it clutters the menu at all so I think that can be up to your discretion

2021-03-29 21:06 UTC, dougkenik commented
> > I turned off showing the images, but the slider is still there. Do you think the slider should disappear too?
> 
> I don't think it will be used that much in custom mode since it only allows the selection of 4 values but I also don't think that it clutters the menu at all so I think that can be up to your discretion

Ok - I turned it off in custom mode... let's see what the resident "expert mode user" says

2021-03-29 21:08 UTC, dougkenik commented
I forgot to add the triad to the scene. Feel free to review and provide feedback - I will update everyone when I get the triad back in to the scene

2021-03-29 21:19 UTC, colman-hartinger commented
Also I think it could be a good Idea to limit the selection angle to 90 degrees. From the parts I was testing with it seemed like any value over 90 would select every triangle

2021-03-30 02:26 UTC, dougkenik commented
Triad is in the scene now

2021-03-30 13:54 UTC, bradymadams requested changes
A code only review. I'll run through the functionality in a separate review.

2021-03-30 14:13 UTC, dougkenik commented on SmartSlicePlugin/components/Triad.py
> +    """
It was all embedded in BuildVolume. I had to copy it over and create a component

2021-03-30 14:18 UTC, dougkenik commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +        if not bc.meta["type"]:
Good catch

2021-03-30 14:18 UTC, dougkenik commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +            controller.getScene().getRoot().addChild(self._triad)
I think we can. I'll try it out - the triad isn't moving when the machine changes right now, so I'm also debugging that

2021-03-30 15:07 UTC, dougkenik commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +            controller.getScene().getRoot().addChild(self._triad)
This won't work - it changes the position of the triad, and I can't figure out how to get it to the correct position

2021-03-30 16:13 UTC, bradymadams commented
Playing around with the flood selection a little bit and I have a couple comments. Overall it works nicely and this is going to be a great enhancement for the plugin.

1. On complex meshes this functionality can result in an enormous amount of triangles being selected. I think we should suppress the printing of the list of triangles if the list exceeds some length. I think anything more than 100 is TMI for debugging and we could just print the length of the list instead.
2. The UI becomes unresponsive and hard to use as you get into angles that result in a large selection. I think we need to do two things:
 a. Offload selection work to a UM.Job
 b. Figure out a way to "ignore" intermediate angles as the user adjusts the slider, so we're not wasting a bunch of time selecting on an angle that isn't even of interest. I can expand on that if that doesn't make sense.

2021-03-30 16:19 UTC, dougkenik commented
> > 1. There is a flag in the QML Slider to only update after the slider is adjusted. Quick fix
> 
> But I think we should still offload to a UM.Job. The UI locks up as it's doing the search and the final selection is large.

Then yeah - let's create a new GH issue and put it in the backlog

2021-03-30 16:25 UTC, bradymadams commented
#494

2021-03-30 16:33 UTC, bradymadams commented
1. In normal selection there are times where I click to rotate the blue rotator but it seems to capture the invisible green rotator and rotates the arrow out of plane.
2. In custom selection the blue rotator is nicely constrained to trotate around a constant vector, but the green rotator seems to "wander".

2021-03-30 17:39 UTC, colman-hartinger reviewed
Code looks really good just a couple comments

2021-03-30 17:39 UTC, colman-hartinger commented on SmartSlicePlugin/select_tool/LoadRotator.py
> +            )
Do you think this can be cleaned up a bit? the only differing values are the angles and colors which leads me to believe that this can be consolidated. Also is there a reason why radians and degrees are being used? I think that could lead to some confusion

2021-03-30 17:39 UTC, colman-hartinger commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +        self.toolsChanged.emit()
why is 'toolsChanged' being emitted when a face is selected?

2021-03-30 19:02 UTC, dougkenik commented
> 1. In normal selection there are times where I click to rotate the blue rotator but it seems to capture the invisible green rotator and rotates the arrow out of plane.
> 2. In custom selection the blue rotator is nicely constrained to trotate around a constant vector, but the green rotator seems to "wander".

@bradymadams - both of these should be fixed now

2021-03-30 19:04 UTC, dougkenik commented on SmartSlicePlugin/select_tool/LoadRotator.py
> +            )
I don't think this can be cleaned up much more. I am relying on a method in UM.Mesh.MeshBuilder to build the pyramids and donuts, so I have to align with their inputs

2021-03-30 21:57 UTC, colman-hartinger requested changes
Code looks good, going to test out the ui a bit more but there is still a merge conflict with SmartSlicePlugin/stage/SmartSliceScene.py that needs to be resolved

2021-03-30 22:30 UTC, colman-hartinger commented
@dougkenik I'm getting this fatal error when switching to the smart slice scene after loading in any part
```
Traceback (most recent call last):
  File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/select_tool/BoundaryConditionList.py", line 283, in activate
    self.add()
  File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/select_tool/BoundaryConditionList.py", line 316, in add
    self._smart_slice_scene_node.addFace(bc)
  File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/stage/SmartSliceScene.py", line 671, in addFace
    self.faceAdded.emit(bc)
  File "/home/shasta/PycharmProjects/Cura/Uranium/UM/Signal.py", line 219, in emit
    self.__performEmit(*args, **kwargs)
  File "/home/shasta/PycharmProjects/Cura/Uranium/UM/Signal.py", line 332, in __performEmit
    func(dest, *args, **kwargs)
  File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/SmartSlicePropertyHandler.py", line 134, in _faceAdded
    self.confirmPendingChanges(self._root)
  File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/SmartSlicePropertyHandler.py", line 366, in confirmPendingChanges
    self.connector.updateStatus()
  File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/SmartSliceCloudConnector.py", line 1061, in updateStatus
    job, self._proxy.errors = self.smartSliceJobHandle.checkJob(show_extruder_warnings=show_warnings)
  File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/SmartSliceJobHandler.py", line 165, in checkJob
    job.chop.steps = smart_sliceScene_node.createSteps(transform_bcs=not writing_workspace)
  File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/stage/SmartSliceScene.py", line 747, in createSteps
    bc = bc_node.pywimBoundaryCondition(step, mesh_rotation, transform_bcs)
  File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/stage/SmartSliceScene.py", line 251, in pywimBoundaryCondition
    anchor.meta["type"] = self.surface_type.value
AttributeError: 'FixedBoundaryCondition' object has no attribute 'meta'
```

2021-03-30 23:43 UTC, dougkenik commented
> @dougkenik I'm getting this fatal error when switching to the smart slice scene after loading in any part
> 
> ```
> Traceback (most recent call last):
>   File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/select_tool/BoundaryConditionList.py", line 283, in activate
>     self.add()
>   File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/select_tool/BoundaryConditionList.py", line 316, in add
>     self._smart_slice_scene_node.addFace(bc)
>   File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/stage/SmartSliceScene.py", line 671, in addFace
>     self.faceAdded.emit(bc)
>   File "/home/shasta/PycharmProjects/Cura/Uranium/UM/Signal.py", line 219, in emit
>     self.__performEmit(*args, **kwargs)
>   File "/home/shasta/PycharmProjects/Cura/Uranium/UM/Signal.py", line 332, in __performEmit
>     func(dest, *args, **kwargs)
>   File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/SmartSlicePropertyHandler.py", line 134, in _faceAdded
>     self.confirmPendingChanges(self._root)
>   File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/SmartSlicePropertyHandler.py", line 366, in confirmPendingChanges
>     self.connector.updateStatus()
>   File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/SmartSliceCloudConnector.py", line 1061, in updateStatus
>     job, self._proxy.errors = self.smartSliceJobHandle.checkJob(show_extruder_warnings=show_warnings)
>   File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/SmartSliceJobHandler.py", line 165, in checkJob
>     job.chop.steps = smart_sliceScene_node.createSteps(transform_bcs=not writing_workspace)
>   File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/stage/SmartSliceScene.py", line 747, in createSteps
>     bc = bc_node.pywimBoundaryCondition(step, mesh_rotation, transform_bcs)
>   File "/home/shasta/PycharmProjects/Cura/Cura/plugins/SmartSlicePlugin/stage/SmartSliceScene.py", line 251, in pywimBoundaryCondition
>     anchor.meta["type"] = self.surface_type.value
> AttributeError: 'FixedBoundaryCondition' object has no attribute 'meta'
> ```

Switch to pywim r21.0

2021-03-31 16:00 UTC, bradymadams commented
> > 1. In normal selection there are times where I click to rotate the blue rotator but it seems to capture the invisible green rotator and rotates the arrow out of plane.
> > 2. In custom selection the blue rotator is nicely constrained to trotate around a constant vector, but the green rotator seems to "wander".
> 
> @bradymadams - both of these should be fixed now

Those both look good now. When I first open custom selection and click a face sometimes only the initial triangle is selected. If I adjust the slider up and then back down to 1 then more triangles are selected. I'm guessing the internal angle is initially set to 0.

2021-03-31 16:24 UTC, colman-hartinger commented
@dougkenik I think the triad should be anchored in the upper right corner. How it is now its very easy to zoom in and have it disappear or be blocked by the load selection menu. Also I found a minor bug  where when switching into custom mode the load arrow direction gets flipped.


![block1](https://user-images.githubusercontent.com/62404177/113177801-264fed80-920b-11eb-8a1b-3c2f686af816.gif)

2021-03-31 16:27 UTC, dougkenik commented
> @dougkenik I think the triad should be anchored in the upper right corner. How it is now its very easy to zoom in and have it disappear or be blocked by the load selection menu. Also I found a minor bug where when switching into custom mode the load arrow direction gets flipped.
> 
> ![block1](https://user-images.githubusercontent.com/62404177/113177801-264fed80-920b-11eb-8a1b-3c2f686af816.gif)

Anchoring it the upper right is super difficult. I used the position that Cura uses for the build plate. The load dialog is movable - maybe I need to make that clearer?

2021-03-31 16:29 UTC, colman-hartinger commented
> Anchoring it the upper right is super difficult. I used the position that Cura uses for the build plate. The load dialog is movable - maybe I need to make that clearer?

That makes sense and ya I think it could be clearer that the load dialogs can be moved I remember only figuring that out by accident a couple months ago

2021-03-31 16:59 UTC, dougkenik commented
Ok - I created a ticket to put a move handle on the load dialog. Everything else has been fixed

2021-03-31 20:44 UTC, colman-hartinger requested changes
there is a fatal error when loading a project with custom anchors (custom loads works fine)

Heres the 3mf of a valifated part with custom loads that is causing cura to crash
[UMS5_block1.zip](https://github.com/tetonsim/is-cura-ui/files/6239372/UMS5_block1.zip)

2021-03-31 20:52 UTC, dougkenik commented
> there is a fatal error when loading a project with custom anchors (custom loads works fine)
> 
> Heres the 3mf of a valifated part with custom anchors that is causing cura to crash
> [UMS5_block1.zip](https://github.com/tetonsim/is-cura-ui/files/6239372/UMS5_block1.zip)

Great catch. This is fixed now

2021-03-31 22:34 UTC, colman-hartinger commented
@dougkenik this seems very minor but the load arrow is still exhibiting the same behavior as the gif above when loading in a validated/optimized part. Everything else seems to be working as expected.

3MF: 
[UMS5_model11.zip](https://github.com/tetonsim/is-cura-ui/files/6239900/UMS5_model11.zip)

2021-03-31 23:27 UTC, dougkenik commented
> @dougkenik this seems very minor but the load arrow is still exhibiting the same behavior as the gif above after loading in a validated/optimized part. Everything else seems to be working as expected.
> 
> 3MF:
> [UMS5_model11.zip](https://github.com/tetonsim/is-cura-ui/files/6239900/UMS5_model11.zip)

@colman-hartinger - this only happens when loading in a part? And, what exactly is incorrect? Is it just the rotator handles need to be on the tail, or is the arrow in the wrong position?

2021-03-31 23:35 UTC, colman-hartinger commented
> > @dougkenik this seems very minor but the load arrow is still exhibiting the same behavior as the gif above after loading in a validated/optimized part. Everything else seems to be working as expected.
> > 3MF:
> > [UMS5_model11.zip](https://github.com/tetonsim/is-cura-ui/files/6239900/UMS5_model11.zip)
> 
> @colman-hartinger - this only happens when loading in a part? And, what exactly is incorrect? Is it just the rotator handles need to be on the tail, or is the arrow in the wrong position?

Yea it only happens when loading in a part, the problem seems fixed otherwise. 

![error](https://user-images.githubusercontent.com/62404177/113223878-6208a880-9247-11eb-9f52-ae923cdf34a4.gif)

2021-03-31 23:49 UTC, dougkenik commented
> > > @dougkenik this seems very minor but the load arrow is still exhibiting the same behavior as the gif above after loading in a validated/optimized part. Everything else seems to be working as expected.
> > > 3MF:
> > > [UMS5_model11.zip](https://github.com/tetonsim/is-cura-ui/files/6239900/UMS5_model11.zip)
> > 
> > 
> > @colman-hartinger - this only happens when loading in a part? And, what exactly is incorrect? Is it just the rotator handles need to be on the tail, or is the arrow in the wrong position?
> 
> Yea it only happens when loading in a part, the problem seems fixed otherwise.
> 
> ![error](https://user-images.githubusercontent.com/62404177/113223878-6208a880-9247-11eb-9f52-ae923cdf34a4.gif)

@colman-hartinger - Is the load being saved correctly for you?

2021-04-01 00:10 UTC, colman-hartinger commented
> @colman-hartinger - Is the load direction being saved correctly for you?
ya the load direction is being saved correctly, the bug only occurs when you
 load in a part with custom loads -> switch to normal mode -> switch back to custom

2021-04-01 00:26 UTC, dougkenik commented
@colman-hartinger - got it. I believe this is fixed now. In general, I want to try and keep the handle manipulators on the donuts on the tail of the arrow

2021-04-01 16:04 UTC, colman-hartinger approved these changes
Everything is looking good and is working for me

2021-04-01 17:25 UTC, bradymadams requested changes
Functionality looks good. One thing I noticed was it's hard to set the exact values of the vector if you know what you want because they get normalized. But I think we can address that later after getting feedback.

One comment on the code.

2021-04-01 17:25 UTC, bradymadams commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +            face.surface_angle = bc.meta["angle"]
I'm always a little weary when I see the same key hardcoded multiple times. In these cases I like to use `get` instead. If you ever need to update the key you don't run the risk of missing one of the hardcoded keys. You can also eliminate the `if` statement with `get` by specifying the default:

```python
face.surface_angle = bc.meta.get("angle", face.surface_angle)
```

Similar for "mode" and "criteria", although you may need to tweak it to work with the enum.

For "type" I would just use `get` without the default and then check if the returned value is None.

2021-04-01 20:07 UTC, bradymadams approved these changes
Nice work - this is going to open up a lot of use cases.

2021-04-01 20:08 UTC, merged