R21.0 surface job
tetonsim/is-cura-ui pull request #500
Opened 2021-04-11 22:29 UTC by dougkenik

#494

2021-04-12 16:37 UTC, bradymadams requested changes

2021-04-12 16:37 UTC, bradymadams commented on SmartSlicePlugin/SmartSlicePreferences.py
> +    MaxNodes = "max_nodes"
Since this is referring to STLs vertices would be better nomenclature, IMO, to avoid confusion with FEA models.

2021-04-12 16:37 UTC, bradymadams commented on SmartSlicePlugin/select_tool/SmartSliceSelectTool.py
> +        if bc_node.surface_type == SmartSliceScene.HighlightFace.SurfaceType.Any and len(interactive_mesh.vertices) > self.extension.preferences.getPreference(Preferences.MaxNodes):
Break up long line.

2021-04-12 16:37 UTC, bradymadams commented on SmartSlicePlugin/select_tool/SmartSliceSelectTool.py
> +                self._calculating_surface_job.cancel()
We might need to look into this. As far as I can tell this won't kill the Job if it's already running. So that means if the `JobQueue` contains multiple workers it becomes a race between the existing SurfaceSelectionJob and the new SurfaceSelectionJob and whichever ones finishes last will determine the selected surface the user gets.

And consider if the user switched from surface type of `Any` to something else while the SurfaceSelectionJob is running. The non Any surface will probably select quickly and then the SurfaceSelectionJob will finish later and update the selected surface.

I think one fix would be to (before line 181) check if any SurfaceSelectionJobs are running and if so set a flag in them that they have been "cancelled". They will still need to run to completion (unless we made checks inside the surface selection code for a cancel request), but when the Job finished event signal gets hit it can check if the Job was cancelled or not.

2021-04-13 16:28 UTC, bradymadams requested changes

2021-04-13 16:28 UTC, bradymadams commented on SmartSlicePlugin/select_tool/SmartSliceSelectTool.py
> +        time.sleep(1)
Let's double check if this is necessary or if we can reduce it. I think 1 second on the mesh analysis was fine because it's pretty trivial compared to the one time cost of analyzing the mesh, but for selecting surfaces over and over it might hurt the UX.

If we do need a sleep, let's add a quick comment explaining why. A random `sleep` call usually means we're improperly trying to fix a race condition which isn't necessarily the case here, so let's help the future dev out by explaining what it's for.

2021-04-13 16:30 UTC, bradymadams commented on SmartSlicePlugin/select_tool/SmartSliceSelectTool.py
> +        time.sleep(1)
I don't know if I tried this in the mesh analysis Job, but we might also try calling `Job.yieldThread` which is just a wrapper around `time.sleep(0)`. That might be enough to yield to the UI thread to allow it to show the progress message box.

2021-04-13 17:32 UTC, colman-hartinger approved these changes
Looks good to me

2021-04-13 19:43 UTC, bradymadams approved these changes
Works nicely. Tried to break it, but couldn't.

2021-04-15 15:32 UTC, merged