R21.0 non manifold detection
tetonsim/is-cura-ui pull request #553
Opened 2021-05-17 23:07 UTC by AijunHall

This is expected to work off of my pywim PR: https://github.com/tetonsim/pywim/pull/87

For now I allow non-manifold geometry through with a warning instead of an exception, for ease of testing how often this situation will be brought up.

2021-05-17 23:50 UTC, jlselden requested changes
Just some minor grammar stuff.

2021-05-17 23:51 UTC, jlselden commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +                        title=i18n_catalog.i18n("SmartSlice has detected non manifold geometry"),
Add a period.

2021-05-17 23:51 UTC, jlselden commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +                        text=i18n_catalog.i18n("This may affect the accuracy of anchors and loads"),
Add a period.

2021-05-17 23:51 UTC, jlselden commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +                    i18n_catalog.i18n("SmartSlice can not be used with non manifolds. Please remove the model")
Add a period.

2021-05-17 23:52 UTC, jlselden commented on SmartSlicePlugin/stage/SmartSliceStage.py
>                  Logger.logException("e", "Unable to analyze geometry")
Fix Doug's sloppy grammar by adding a period.

2021-05-18 00:04 UTC, AijunHall commented on SmartSlicePlugin/stage/SmartSliceStage.py
>                  Logger.logException("e", "Unable to analyze geometry")
Should all logExceptions and Message titles have periods?

2021-05-18 00:13 UTC, bradymadams requested changes

2021-05-18 00:13 UTC, bradymadams commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +            except pywim.geom.tri.NonManifold as exc:
You'll need to be careful here. Take a look at `SmartSliceNode.initialize`. If the geometry exceeds a certain size the mesh analysis gets offloaded into a `Job`. If an exception gets thrown in a `Job` it won't get caught here.

2021-05-18 00:13 UTC, bradymadams commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +                    self._mesh_non_manifold_warning_message = Message(
It doesn't look like `self._mesh_non_manifold_warning_message` is used outside of this function, therefore it doesn't need to be a class attribute.

2021-05-18 00:13 UTC, bradymadams commented on SmartSlicePlugin/stage/SmartSliceScene.py
>                  job = AnalyzeMeshJob(mesh_data, step, callback)
I alluded to this in another comment, but we'll also need the same checks when the mesh analysis is done in the `AnalyzeMeshJob`.

2021-05-18 00:14 UTC, jlselden commented on SmartSlicePlugin/stage/SmartSliceStage.py
>                  Logger.logException("e", "Unable to analyze geometry")
In my opinion, if a customer is going to see it, it should be grammatically correct. I think it looks more professional that way. If it's only ever going to be seen by us, it's less important.

2021-05-18 00:15 UTC, bradymadams commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +            except pywim.geom.tri.NonManifold as exc:
Ping me if you need some help understanding the `Job` classes and how they work. They essentially offload a function into another thread so the UI doesn't lock up.

2021-05-18 01:45 UTC, AijunHall commented on SmartSlicePlugin/stage/SmartSliceStage.py
> +            except pywim.geom.tri.NonManifold as exc:
I see where I need to include another mesh warning check in the `Job` now, I just missed it since I didn't immediately see the interactive mesh in that else block.

2021-05-18 20:52 UTC, bradymadams requested changes
Looks pretty good. Just one minor code change request. Can you share a screenshot showing how the message looks?

2021-05-18 20:52 UTC, bradymadams commented on SmartSlicePlugin/stage/SmartSliceScene.py
> +                if any(issubclass(type(warning), pywim.geom.tri.NonManifold) for warning in self._interactive_mesh.warnings()):
When you have an object `isinstance` is preferred over `issubclass`:

```python
isinstance(warning, pywim.geom.tri.NonManifold)
```

2021-05-18 21:07 UTC, AijunHall commented
Heres how the warning message looks @bradymadams .

![image](https://user-images.githubusercontent.com/54338983/118722710-56664680-b7e1-11eb-9dd3-3f86f2620925.png)

But don't I still have to include an exception for potential queued Jobs? You said above that the except catch on line 188 in SmartSliceStage won't catch Job.Errors

I was still working on putting the same exception catch here 

https://github.com/tetonsim/is-cura-ui/blob/0d3c3b4823a18f91027a095f600c652adbdf74d3/SmartSlicePlugin/stage/SmartSliceScene.py#L681-L689

2021-05-18 21:08 UTC, bradymadams commented
> But don't I still have to include an exception for potential queued Jobs? You said above that the except catch on line 188 in SmartSliceStage won't catch Job.Errors
> 
> I was still working on putting the same exception catch here
> 
> https://github.com/tetonsim/is-cura-ui/blob/0d3c3b4823a18f91027a095f600c652adbdf74d3/SmartSlicePlugin/stage/SmartSliceScene.py#L681-L689

No, you're correct. I forgot about that - we need to catch the exception in the Job as well.

2021-05-18 21:09 UTC, bradymadams commented
I was working through a handful of PR reviews and didn't realize you hadn't re-requested my review on this PR yet - that's my bad.

2021-05-18 21:15 UTC, bradymadams commented
Let's change the warning message a little bit. It hard potentially further reaching issues than just the boundary conditions.

> SmartSlice has detected non manifold geometry.
> This may affect the accuracy of anchors and loads.

to

> Warning: the geometry is not manifold.
> Non-manifold geometry may cause unexpected behavior or errors when used with SmartSlice.

2021-05-18 21:37 UTC, AijunHall commented
I wana note that the `Job.Error()` won't force users out of the SmartSliceStage like it does for models of lesser sizes that don't get queued up in `initialize()` I don't know if that's something that needs to be fixed for #478 . That's if pywim has opted to raise Errors instead of storing them in the mesh warning.

The other already existing catchall exception for `Job.Errors()` doesn't kick users out of the SmartSliceStage either.

2021-05-19 16:20 UTC, AijunHall commented
> I see the issue with the exception in the Job not exiting the stage. I think rather than fix that, it probably makes sense to just remove the check for the exceptions so there's no confusion in the future. We can add the checks back in, and add the logic to exit the stage, if we ever decide we need to reject non-manifold geometries. Thoughts?

Sounds good to me, if more non-manifold checks get added in, the way we deal with these mesh warnings is probably going to change anyway.

2021-05-19 20:12 UTC, AijunHall commented
Only the warning exists now

2021-05-20 00:28 UTC, jlselden approved these changes
Looks good to me.

2021-05-20 12:08 UTC, dougkenik approved these changes

2021-05-20 13:02 UTC, bradymadams approved these changes
Looks good @AijunHall

2021-05-20 13:03 UTC, merged