R21.1 mod mesh validation
tetonsim/is-cura-ui pull request #560
Opened 2021-06-17 21:23 UTC by AijunHall

This PR works off my other PR in pywim.

Here I changed the validation in `checkJob` to work per node/mesh, instead of only for the global print config. This way the Top/Bottom Line Directions, Infill Line Directions, and Infill pattern are all validated properly for mod meshes. For mod meshes I use the existing auxiliary dictionary to get properties vs changing the propertyHandler

Without the pywim changes `_getAuxDict` doesn't retrieve certain properties. For example previously:
```
for prop in pywim.smartslice.val.NECESSARY_PRINT_PARAMETERS:
            val = stack.getProperty(prop, "value")
```
infill.pattern, infill.orientation, infill.density all aren't recognized by Cura and return None which causes issues for validation.

An alternative to the pywim changes is putting checks in `_getAuxDict` that change the pywim infill property keys to their Cura equivalents (infill_pattern, infill_sparse_density, etc).

2021-06-18 14:56 UTC, bradymadams commented
Doug and I may not be able to review this for a couple of days, so adding Colman as a reviewer.

2021-06-18 15:58 UTC, colman-hartinger requested changes
Everything is looking pretty good, just some comments about styling and structure. This is just an initial code review so I'll test the functionality in Cura a bit later today

2021-06-18 15:58 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +            extruders += (extruder,)
In python I like to use list comprehensions to create lists of objects rather than create an empty object and add to it. I think a cleaner way could be something like this

```
def setExtruder(stack):
    extruder = pywim.chop.machine.Extruder(diameter=stack.getProperty("machine_nozzle_size", "value"))
    extruder.print_config.auxiliary = self._getAuxDict(stack)
    return extruder

machine_extruder = getNodeActiveExtruder(normal_mesh)
extruders = [setExtruder(extruder_Stack) for extruder_Stack in machine_extruder]
```

2021-06-18 15:58 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +
remove the empty line between if-else. Also instead of checking the length, you can just use `if not parsed_skin_angles`.

2021-06-18 15:58 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                    print_config.skin_orientations.extend(tuple(parsed_skin_angles))
add empty line after if-else statement

2021-06-18 15:58 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                parsed_infill_angles = SettingFunction(infill_angles)(self._propertyHandler)
Does the `SettingFunctoin` return a list? If it doesn't I don't think mixing data types is a good idea and could result in bugs down the line

2021-06-18 15:58 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                    print_config.infill.orientation = parsed_infill_angles[0]
Same  comment as above about no empty space between if-else statements and an empty line after them

2021-06-18 15:58 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                    if len(parsed_infill_angles) > 1:
I don't think this if statement is necessary since it's only used for logging info.  Maybe a better solution would be to just have a log statement in the parent else block saying "Setting infill angle <angle>. Ignoring other angles <other angles>"

2021-06-18 21:01 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                parsed_infill_angles = SettingFunction(infill_angles)(self._propertyHandler)
Yeah `SettingFunction` is only either a list or None as far as I've seen.

2021-06-18 21:58 UTC, colman-hartinger requested changes

2021-06-18 21:58 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +        extruders = ()
No need to initialize extruders here.

2021-06-18 21:58 UTC, colman-hartinger commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +
remove empty line between if-else statement

2021-06-22 21:04 UTC, colman-hartinger approved these changes
Code looks good and seems to fix associated bug

2021-06-24 13:41 UTC, bradymadams approved these changes
Code looks good and the issue is resolved. I did notice another similar issue, but it appears it was an existing issue, so I'll open a separate ticket for it. Nice job @AijunHall

2021-06-24 13:42 UTC, merged