R21.1 checkJob code consolidation
tetonsim/is-cura-ui pull request #574
Opened 2021-08-04 03:26 UTC by AijunHall

My goal is to retain the "top level resources" like the job, errors, and nodes while splitting other functionality into separate methods to try and be more readable and efficient. This is about 80% done I think. 

I still need to make changes to my proposed `_validateConfigs` and `_buildConfigs`. The `normal_mesh` needs to have its own individual mesh config and global config validated at the same time, as mentioned in [561](https://github.com/tetonsim/is-cura-ui/issues/561). I thought I'd managed that, but I still have some work to do. I also need to include typing declarations for these new methods.

Additionally `buildJobFor3mf` will have to be updated to reflect these new print hierarchy changes (including the individual mesh print configs alongside the global/extruder configs). I could either create a new ticket for that, or include the changes here.

2021-08-04 12:51 UTC, dougkenik reviewed
In general this seems to be consolidating a tiny bit. One thing I would recommend is to return a set of new errors from your functions and add them to cura_errors instead of passing cura_errors around to them

2021-08-04 12:51 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +        if not printable_nodes:
Might want to keep the check for the length being zero here as well, just in case

2021-08-04 12:51 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +        smart_sliceScene_node = findChildSceneNode(normal_node, Root)
Naming here is off - smartslice_scene_node might be better

2021-08-05 03:22 UTC, AijunHall commented
I was running into an issue where if a node had a valid mesh infill pattern, but an invalid extruder infill pattern, the error wouldn't be caught. I added a Infill pattern error creation in the global print config validation for now to fix that, rather than letting it go to pywim, as is done for the meshes. I'll look more into that to see if its necessary.

2021-08-05 16:58 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                ))
Why is special handling of the normal mesh infill pattern necessary? If possible, I'd prefer we use a consolidated check in pywim.

2021-08-05 17:02 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +from cura.Scene.CuraSceneNode import CuraSceneNode
When I was creating the cura node typing declarations for my other functions, I was running into issues with cura not being defined. This import is solely for the typing.

`all_nodes: List[CuraSceneNode]`

Is it appropriate to have an import purely for the typing, or should I be doing the typing differently?

2021-08-05 17:06 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                ))
Looking into this right now, I agree that we should be using the consolidated check in pywim.

Might be able to get rid of this by adding the global print config to the job's meshes

2021-08-05 17:07 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +from cura.Scene.CuraSceneNode import CuraSceneNode
I'm fine with it. [Some code bases will add a conditional where the import is only done on type checking.](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING)

2021-08-05 17:40 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                ))
@bradymadams Just tried this and it seems to work.

What do you think about adding an additional mesh to the job meshes that holds the global print config? That way the special handling here isn't necessary. 

One issue with this though is the pywim error message might be confusing to users, depending on what we name the mesh that holds the global print config
![image](https://user-images.githubusercontent.com/54338983/128395002-a2e6ef19-ddd1-4a89-98e4-3414d360da65.png)

Another option I see is creating a method in pywim dedicated to validating the global print config separate from the existing `job.validate()` which works through the meshes. I could be missing an easier solution here though. What are your thoughts?

2021-08-06 12:38 UTC, dougkenik requested changes
This is looking much cleaner, and I like how we have broken out the major parts of the code base.

2021-08-06 12:38 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                ))
I would prefer to move all error checking into job.validate. I believe that function is setup to use the global print config whenever a mesh config is not set. If not, then we might need to work out what to do in that function to catch these errors. I also am uneasy adding the normal mesh again just to check the global print config... there should be a better solution for this.

2021-08-06 17:20 UTC, AijunHall commented
I'll see what I can do to further consolidate this validation towards pywim and `job.validate()`

2021-08-12 20:38 UTC, dougkenik commented
@AijunHall - what do you mean by  "valid" and "invalid" in this context?

2021-08-12 20:54 UTC, AijunHall commented
> @AijunHall - what do you mean by "valid" and "invalid" in this context?

@dougkenik By valid, I mean a user input from the Top/Bottom Line Directions, Infill Directions, and Infill Pattern entry fields that is acceptable to enter into the print configs, and usable on the backend for the solver. The UM SettingFunction does some of this work in interpreting what is a "valid" or "invalid" user entry, and I try to translate that into our config.

By Invalid, I mean a user input that isn't acceptable/usable. For example we previously had crashes when users would enter a string list like ` 1, 2, 3]` into the Top/Bottom Line Directions or Infill Directions because of how the UM SettingFunction would translate that to our print config.

My pywim PR is trying to offload the functionality that makes that distinction of what is "valid" and "invalid"

2021-08-12 20:57 UTC, dougkenik commented
> > @AijunHall - what do you mean by "valid" and "invalid" in this context?
> 
> @dougkenik By valid, I mean a user input from the Top/Bottom Line Directions, Infill Directions, and Infill Pattern entry fields that is acceptable to enter into the print configs, and usable on the backend for the solver. The UM SettingFunction does some of this work in interpreting what is a "valid" or "invalid" user entry, and I try to translate that into our config.
> 
> By Invalid, I mean a user input that isn't acceptable/usable. For example we previously had crashes when users would enter a string list like ` 1, 2, 3]` into the Top/Bottom Line Directions or Infill Directions because of how the UM SettingFunction would translate that to our print config.
> 
> To be as simple as possible I really mean a valid list value, and an invalid list value
> 
> My pywim PR is trying to offload the functionality that makes that distinction of what is "valid" and "invalid"

Ok - so if it is invalid, shouldn't we be catching that prior to submitting the job? It should be caught as soon as it's input and invalid by the plugin job checking, shouldn't it?

2021-08-12 21:36 UTC, AijunHall commented
> Ok - so if it is invalid, shouldn't we be catching that prior to submitting the job? It should be caught as soon as it's input and invalid by the plugin job checking, shouldn't it?

@dougkenik Thats what we were doing previously here within `checkJob`, adding the errors as we caught them plugin-side instead of letting it go to `job.validate()`. We had special handling of these fields that I've tried to consolidate into pywim.

My question now is what part of the validation would we like to consolidate into pywim? Should we have plugin-side error creation for these fields as well as pywim-side validation? Or should I revert back to previous commits in this PR where I included special error handling before validating the job? Thats what my`_validateConfigs` function was doing before.

I've moved all print config error checking consolidation into pywim based off you and brady's comments above mentioning you'd both like to get rid of the plugin-side handling of errors. But if its more desirable to add it back, that works as well.

2021-08-12 23:27 UTC, dougkenik approved these changes

2021-08-17 14:07 UTC, bradymadams requested changes
Just a few minor requests.

2021-08-17 14:07 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                if isinstance(parsed_value, list):
If line 490 evaluates to false then `parsed_value` will be undefined here.

2021-08-17 14:07 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +    def _validateMaterial(self, normal_node: CuraSceneNode, show_material_warnings: bool) -> Tuple[Optional[pywim.fea.model.Material], List[pywim.smartslice.val.InvalidSetup]]:
Break up long line. This line exceeds the width of the code pane in Github when reviewing the PR. Take a look at the code changes under this PR and you should see what I mean.

2021-08-17 14:07 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +    def _validateExtruders(self, all_nodes: List[CuraSceneNode], app: CuraApplication, show_material_warnings: bool) -> List[pywim.smartslice.val.InvalidSetup]:
Break up long line.

2021-08-17 14:07 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +BuiltConfigs = Tuple[List[pywim.chop.mesh.Mesh], List[pywim.chop.machine.Extruder], pywim.am.Config]
Really nice use of a type alias :+1:

2021-08-18 04:33 UTC, AijunHall commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                if isinstance(parsed_value, list):
Thanks for catching this

2021-08-23 14:17 UTC, bradymadams requested changes
Just need a slight format adjustment to the multi-line function definitions.

2021-08-23 14:17 UTC, bradymadams commented on SmartSlicePlugin/SmartSliceJobHandler.py
> +                           show_material_warnings: bool) -> List[pywim.smartslice.val.InvalidSetup]:
Our preferred multi-line style for argument lists and function calls is to only add one indent level for the arguments, and then place the closing brace/bracket at the same level of indent as the first line. For example:

```python
def _validateExtruders(
    self,
    all_nodes: List[CuraSceneNode],
    app: CuraApplication,
    show_material_warnings: bool
) -> List[pywim.smartslice.val.InvalidSetup]:
```

You might see the style you used elsewhere in this code base, but that would be code from before we adopted a more "official" style guide.

2021-08-24 19:47 UTC, bradymadams approved these changes

2021-08-24 19:49 UTC, merged