R21.1 internet connection error help doc
tetonsim/is-cura-ui pull request #594
Opened 2021-09-03 00:19 UTC by AijunHall

Heres what the message looks like now.

![image](https://user-images.githubusercontent.com/54338983/131931551-06cf7e5c-2329-44d2-991e-d03225f76308.png)

"Please check to ensure you have an internet connection. If you do have an internet connection, and are still receiving this error, please refer to _support_ or alternatively _contact_ us."

2021-09-03 00:20 UTC, AijunHall commented on SmartSlicePlugin/plugin.json
> -    "version": "21.1.10",
Forgot to increment the version for the `plugin.json` on my last ticket. It should be `r21.1.12` now to align with the `package.json`

2021-09-03 12:29 UTC, dougkenik requested changes

2021-09-03 12:29 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceAPI.py
> +                "<A HREF='" + self._url_handler.helpEmail + "?subject=SmartSlice Cannot Connect Error'>contact us</A>."
I would remove "contact us" - some people's default email client doesn't open correctly.

2021-09-03 12:29 UTC, dougkenik commented on SmartSlicePlugin/SmartSliceAPI.py
> +                "<A HREF='" + self._url_handler.errorGuide + "#unable_to_contact_servers'>support</A> or alternatively "
I would point users here instead.
https://help.tetonsim.com/internet-connectivity

Add this URL to the `URLHandler ` class

2021-09-03 22:02 UTC, AijunHall commented
New message

![image](https://user-images.githubusercontent.com/54338983/132069129-f894113c-7d04-4a9c-81a4-e359f08fd796.png)

2021-09-07 00:07 UTC, dougkenik approved these changes

2021-09-07 15:24 UTC, bradymadams approved these changes

2021-09-07 15:24 UTC, merged