R21.1 cutting mesh node
tetonsim/is-cura-ui pull request #597
Opened 2021-09-15 20:00 UTC by AijunHall

Linked [PR](https://github.com/tetonsim/pywim/pull/102)

Made changes to our getNode methods in utils in order to detect cutting meshes, so that we can invalidate them in pywim. Previously `getModifierMeshes` only returned infill meshes. 

Now these lines properly detect and create cutting meshes.

https://github.com/tetonsim/is-cura-ui/blob/de9b6d26bfa45a5c754c5fc0911bc750ea6851ed/SmartSlicePlugin/SmartSliceJobHandler.py#L104

https://github.com/tetonsim/is-cura-ui/blob/de9b6d26bfa45a5c754c5fc0911bc750ea6851ed/SmartSlicePlugin/SmartSliceJobHandler.py#L166-L167

2021-09-15 20:02 UTC, AijunHall commented
![image](https://user-images.githubusercontent.com/54338983/133501408-821b50f1-d434-4a5d-b3c3-86d3c9393fbe.png)

Here's what the error message looks like

2021-09-16 12:53 UTC, bradymadams requested changes
Looks good - just one request on the resolution text. Let's change it to `Change mesh {mesh_name} to an infill mesh or remove it`.

2021-09-16 19:51 UTC, AijunHall commented
@bradymadams Made the resolution text change in pywim now

![image](https://user-images.githubusercontent.com/54338983/133676599-63edf314-f13c-4e14-895c-c64c7e332563.png)

2021-09-16 19:53 UTC, bradymadams approved these changes

2021-09-16 21:09 UTC, dougkenik approved these changes

2021-09-16 21:13 UTC, merged